// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type AddressElement struct {
	attributes addressAttrs
	children   []htemel.Node
	skipRender bool
}

// Address creates a tag <address> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The address element represents the contact information for its nearest article or body element ancestor. If that is the body element, then the contact information applies to the document as a whole.
func Address(children ...htemel.Node) *AddressElement {
	node := &AddressElement{
		children:   children,
		attributes: make(addressAttrs),
	}

	return node
}

func AddressIf(condition bool, children ...htemel.Node) *AddressElement {
	if condition {
		return Address(children...)
	}

	return &AddressElement{
		children:   children,
		attributes: make(addressAttrs),
		skipRender: true,
	}
}

func AddressTernary(condition bool, true htemel.Node, false htemel.Node) *AddressElement {
	if condition {
		return Address(true)
	}
	return Address(false)
}

// Children appends children to this element.
func (e *AddressElement) Children(children ...htemel.Node) *AddressElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *AddressElement) With(fn func(*AddressElement)) *AddressElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *AddressElement) Text(text string) *AddressElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *AddressElement) Textf(format string, args ...any) *AddressElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *AddressElement) AddClass(classes ...string) *AddressElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *AddressElement) ToggleClass(class string, enable bool) *AddressElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type AddressAutocapitalize string

const (
	AddressAutocapitalizeNone       AddressAutocapitalize = "none"
	AddressAutocapitalizeOff        AddressAutocapitalize = "off"
	AddressAutocapitalizeOn         AddressAutocapitalize = "on"
	AddressAutocapitalizeSentences  AddressAutocapitalize = "sentences"
	AddressAutocapitalizeWords      AddressAutocapitalize = "words"
	AddressAutocapitalizeCharacters AddressAutocapitalize = "characters"
)

type AddressAutocorrect string

const (
	AddressAutocorrectOff   AddressAutocorrect = "off"
	AddressAutocorrectOn    AddressAutocorrect = "on"
	AddressAutocorrectEmpty AddressAutocorrect = ""
)

type AddressContenteditable string

const (
	AddressContenteditableFalse         AddressContenteditable = "false"
	AddressContenteditablePlaintextOnly AddressContenteditable = "plaintext-only"
	AddressContenteditableTrue          AddressContenteditable = "true"
	AddressContenteditableEmpty         AddressContenteditable = ""
)

type AddressDir string

const (
	AddressDirAuto AddressDir = "auto"
	AddressDirLtr  AddressDir = "ltr"
	AddressDirRtl  AddressDir = "rtl"
)

type AddressDraggable string

const (
	AddressDraggableTrue  AddressDraggable = "true"
	AddressDraggableFalse AddressDraggable = "false"
)

type AddressEnterkeyhint string

const (
	AddressEnterkeyhintDone     AddressEnterkeyhint = "done"
	AddressEnterkeyhintEnter    AddressEnterkeyhint = "enter"
	AddressEnterkeyhintGo       AddressEnterkeyhint = "go"
	AddressEnterkeyhintNext     AddressEnterkeyhint = "next"
	AddressEnterkeyhintPrevious AddressEnterkeyhint = "previous"
	AddressEnterkeyhintSearch   AddressEnterkeyhint = "search"
	AddressEnterkeyhintSend     AddressEnterkeyhint = "send"
)

type AddressHidden string

const (
	AddressHiddenHidden     AddressHidden = "hidden"
	AddressHiddenUntilFound AddressHidden = "until-found"
	AddressHiddenEmpty      AddressHidden = ""
)

type AddressInputmode string

const (
	AddressInputmodeDecimal AddressInputmode = "decimal"
	AddressInputmodeEmail   AddressInputmode = "email"
	AddressInputmodeNone    AddressInputmode = "none"
	AddressInputmodeNumeric AddressInputmode = "numeric"
	AddressInputmodeSearch  AddressInputmode = "search"
	AddressInputmodeTel     AddressInputmode = "tel"
	AddressInputmodeText    AddressInputmode = "text"
	AddressInputmodeUrl     AddressInputmode = "url"
)

type AddressSpellcheck string

const (
	AddressSpellcheckFalse AddressSpellcheck = "false"
	AddressSpellcheckTrue  AddressSpellcheck = "true"
	AddressSpellcheckEmpty AddressSpellcheck = ""
)

type AddressTranslate string

const (
	AddressTranslateNo    AddressTranslate = "no"
	AddressTranslateYes   AddressTranslate = "yes"
	AddressTranslateEmpty AddressTranslate = ""
)

type AddressWritingsuggestions string

const (
	AddressWritingsuggestionsFalse AddressWritingsuggestions = "false"
	AddressWritingsuggestionsTrue  AddressWritingsuggestions = "true"
	AddressWritingsuggestionsEmpty AddressWritingsuggestions = ""
)

type addressAttrs map[string]any

func (e *AddressElement) AriaUnsafe(name string, s string) *AddressElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *AddressElement) Aria(name string, s string) *AddressElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *AddressElement) Autocapitalize(a AddressAutocapitalize) *AddressElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *AddressElement) Autocorrect(a AddressAutocorrect) *AddressElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *AddressElement) Autofocus(b bool) *AddressElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *AddressElement) Class(s ...string) *AddressElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *AddressElement) Contenteditable(a AddressContenteditable) *AddressElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *AddressElement) DataUnsafe(name string, s string) *AddressElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *AddressElement) Data(name string, s string) *AddressElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *AddressElement) Dir(a AddressDir) *AddressElement {
	e.attributes["dir"] = a

	return e
}

func (e *AddressElement) Draggable(a AddressDraggable) *AddressElement {
	e.attributes["draggable"] = a

	return e
}

func (e *AddressElement) Enterkeyhint(a AddressEnterkeyhint) *AddressElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *AddressElement) Hidden(a AddressHidden) *AddressElement {
	e.attributes["hidden"] = a

	return e
}

func (e *AddressElement) Id(s string) *AddressElement {
	e.attributes["id"] = s

	return e
}

func (e *AddressElement) Inert(b bool) *AddressElement {
	e.attributes["inert"] = b

	return e
}

func (e *AddressElement) Inputmode(a AddressInputmode) *AddressElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *AddressElement) Itemid(s string) *AddressElement {
	e.attributes["itemid"] = s

	return e
}

func (e *AddressElement) Itemprop(s ...string) *AddressElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *AddressElement) Itemref(s ...string) *AddressElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *AddressElement) Itemscope(b bool) *AddressElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *AddressElement) Itemtype(s ...string) *AddressElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *AddressElement) Lang(s string) *AddressElement {
	e.attributes["lang"] = s

	return e
}

func (e *AddressElement) Nonce(s string) *AddressElement {
	e.attributes["nonce"] = s

	return e
}

func (e *AddressElement) Popover(s string) *AddressElement {
	e.attributes["popover"] = s

	return e
}

func (e *AddressElement) Role(s string) *AddressElement {
	e.attributes["role"] = s

	return e
}

func (e *AddressElement) Slot(s string) *AddressElement {
	e.attributes["slot"] = s

	return e
}

func (e *AddressElement) Spellcheck(a AddressSpellcheck) *AddressElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *AddressElement) Style(s string) *AddressElement {
	e.attributes["style"] = s

	return e
}

func (e *AddressElement) Tabindex(i int) *AddressElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *AddressElement) Title(s string) *AddressElement {
	e.attributes["title"] = s

	return e
}

func (e *AddressElement) Translate(a AddressTranslate) *AddressElement {
	e.attributes["translate"] = a

	return e
}

func (e *AddressElement) Writingsuggestions(a AddressWritingsuggestions) *AddressElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *AddressElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<address")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</address>")

	_, err := io.WriteString(w, sb.String())
	return err
}
