// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type AudioElement struct {
	attributes audioAttrs
	children   []htemel.Node
	skipRender bool
}

// Audio creates a tag <audio> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: An audio element represents a sound or audio stream.
func Audio(children ...htemel.Node) *AudioElement {
	node := &AudioElement{
		children:   children,
		attributes: make(audioAttrs),
	}

	return node
}

func AudioIf(condition bool, children ...htemel.Node) *AudioElement {
	if condition {
		return Audio(children...)
	}

	return &AudioElement{
		children:   children,
		attributes: make(audioAttrs),
		skipRender: true,
	}
}

func AudioTernary(condition bool, true htemel.Node, false htemel.Node) *AudioElement {
	if condition {
		return Audio(true)
	}
	return Audio(false)
}

// Children appends children to this element.
func (e *AudioElement) Children(children ...htemel.Node) *AudioElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *AudioElement) With(fn func(*AudioElement)) *AudioElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *AudioElement) Text(text string) *AudioElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *AudioElement) Textf(format string, args ...any) *AudioElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *AudioElement) AddClass(classes ...string) *AudioElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *AudioElement) ToggleClass(class string, enable bool) *AudioElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type AudioCrossorigin string

const (
	AudioCrossoriginAnonymous      AudioCrossorigin = "anonymous"
	AudioCrossoriginUseCredentials AudioCrossorigin = "use-credentials"
	AudioCrossoriginEmpty          AudioCrossorigin = ""
)

type AudioPreload string

const (
	AudioPreloadMetadata AudioPreload = "metadata"
	AudioPreloadNone     AudioPreload = "none"
	AudioPreloadAuto     AudioPreload = "auto"
	AudioPreloadEmpty    AudioPreload = ""
)

type AudioAutocapitalize string

const (
	AudioAutocapitalizeWords      AudioAutocapitalize = "words"
	AudioAutocapitalizeCharacters AudioAutocapitalize = "characters"
	AudioAutocapitalizeNone       AudioAutocapitalize = "none"
	AudioAutocapitalizeOff        AudioAutocapitalize = "off"
	AudioAutocapitalizeOn         AudioAutocapitalize = "on"
	AudioAutocapitalizeSentences  AudioAutocapitalize = "sentences"
)

type AudioAutocorrect string

const (
	AudioAutocorrectOff   AudioAutocorrect = "off"
	AudioAutocorrectOn    AudioAutocorrect = "on"
	AudioAutocorrectEmpty AudioAutocorrect = ""
)

type AudioContenteditable string

const (
	AudioContenteditableTrue          AudioContenteditable = "true"
	AudioContenteditableFalse         AudioContenteditable = "false"
	AudioContenteditablePlaintextOnly AudioContenteditable = "plaintext-only"
	AudioContenteditableEmpty         AudioContenteditable = ""
)

type AudioDir string

const (
	AudioDirRtl  AudioDir = "rtl"
	AudioDirAuto AudioDir = "auto"
	AudioDirLtr  AudioDir = "ltr"
)

type AudioDraggable string

const (
	AudioDraggableFalse AudioDraggable = "false"
	AudioDraggableTrue  AudioDraggable = "true"
)

type AudioEnterkeyhint string

const (
	AudioEnterkeyhintDone     AudioEnterkeyhint = "done"
	AudioEnterkeyhintEnter    AudioEnterkeyhint = "enter"
	AudioEnterkeyhintGo       AudioEnterkeyhint = "go"
	AudioEnterkeyhintNext     AudioEnterkeyhint = "next"
	AudioEnterkeyhintPrevious AudioEnterkeyhint = "previous"
	AudioEnterkeyhintSearch   AudioEnterkeyhint = "search"
	AudioEnterkeyhintSend     AudioEnterkeyhint = "send"
)

type AudioHidden string

const (
	AudioHiddenHidden     AudioHidden = "hidden"
	AudioHiddenUntilFound AudioHidden = "until-found"
	AudioHiddenEmpty      AudioHidden = ""
)

type AudioInputmode string

const (
	AudioInputmodeUrl     AudioInputmode = "url"
	AudioInputmodeDecimal AudioInputmode = "decimal"
	AudioInputmodeEmail   AudioInputmode = "email"
	AudioInputmodeNone    AudioInputmode = "none"
	AudioInputmodeNumeric AudioInputmode = "numeric"
	AudioInputmodeSearch  AudioInputmode = "search"
	AudioInputmodeTel     AudioInputmode = "tel"
	AudioInputmodeText    AudioInputmode = "text"
)

type AudioSpellcheck string

const (
	AudioSpellcheckFalse AudioSpellcheck = "false"
	AudioSpellcheckTrue  AudioSpellcheck = "true"
	AudioSpellcheckEmpty AudioSpellcheck = ""
)

type AudioTranslate string

const (
	AudioTranslateNo    AudioTranslate = "no"
	AudioTranslateYes   AudioTranslate = "yes"
	AudioTranslateEmpty AudioTranslate = ""
)

type AudioWritingsuggestions string

const (
	AudioWritingsuggestionsFalse AudioWritingsuggestions = "false"
	AudioWritingsuggestionsTrue  AudioWritingsuggestions = "true"
	AudioWritingsuggestionsEmpty AudioWritingsuggestions = ""
)

type audioAttrs map[string]any

func (e *AudioElement) Src(s string) *AudioElement {
	e.attributes["src"] = s

	return e
}

func (e *AudioElement) Crossorigin(a AudioCrossorigin) *AudioElement {
	e.attributes["crossorigin"] = a

	return e
}

func (e *AudioElement) Preload(a AudioPreload) *AudioElement {
	e.attributes["preload"] = a

	return e
}

func (e *AudioElement) Autoplay(b bool) *AudioElement {
	e.attributes["autoplay"] = b

	return e
}

func (e *AudioElement) Playsinline(b bool) *AudioElement {
	e.attributes["playsinline"] = b

	return e
}

func (e *AudioElement) Loop(b bool) *AudioElement {
	e.attributes["loop"] = b

	return e
}

func (e *AudioElement) Muted(b bool) *AudioElement {
	e.attributes["muted"] = b

	return e
}

func (e *AudioElement) Controls(b bool) *AudioElement {
	e.attributes["controls"] = b

	return e
}

func (e *AudioElement) AriaUnsafe(name string, s string) *AudioElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *AudioElement) Aria(name string, s string) *AudioElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *AudioElement) Autocapitalize(a AudioAutocapitalize) *AudioElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *AudioElement) Autocorrect(a AudioAutocorrect) *AudioElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *AudioElement) Autofocus(b bool) *AudioElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *AudioElement) Class(s ...string) *AudioElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *AudioElement) Contenteditable(a AudioContenteditable) *AudioElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *AudioElement) DataUnsafe(name string, s string) *AudioElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *AudioElement) Data(name string, s string) *AudioElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *AudioElement) Dir(a AudioDir) *AudioElement {
	e.attributes["dir"] = a

	return e
}

func (e *AudioElement) Draggable(a AudioDraggable) *AudioElement {
	e.attributes["draggable"] = a

	return e
}

func (e *AudioElement) Enterkeyhint(a AudioEnterkeyhint) *AudioElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *AudioElement) Hidden(a AudioHidden) *AudioElement {
	e.attributes["hidden"] = a

	return e
}

func (e *AudioElement) Id(s string) *AudioElement {
	e.attributes["id"] = s

	return e
}

func (e *AudioElement) Inert(b bool) *AudioElement {
	e.attributes["inert"] = b

	return e
}

func (e *AudioElement) Inputmode(a AudioInputmode) *AudioElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *AudioElement) Itemid(s string) *AudioElement {
	e.attributes["itemid"] = s

	return e
}

func (e *AudioElement) Itemprop(s ...string) *AudioElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *AudioElement) Itemref(s ...string) *AudioElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *AudioElement) Itemscope(b bool) *AudioElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *AudioElement) Itemtype(s ...string) *AudioElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *AudioElement) Lang(s string) *AudioElement {
	e.attributes["lang"] = s

	return e
}

func (e *AudioElement) Nonce(s string) *AudioElement {
	e.attributes["nonce"] = s

	return e
}

func (e *AudioElement) Popover(s string) *AudioElement {
	e.attributes["popover"] = s

	return e
}

func (e *AudioElement) Role(s string) *AudioElement {
	e.attributes["role"] = s

	return e
}

func (e *AudioElement) Slot(s string) *AudioElement {
	e.attributes["slot"] = s

	return e
}

func (e *AudioElement) Spellcheck(a AudioSpellcheck) *AudioElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *AudioElement) Style(s string) *AudioElement {
	e.attributes["style"] = s

	return e
}

func (e *AudioElement) Tabindex(i int) *AudioElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *AudioElement) Title(s string) *AudioElement {
	e.attributes["title"] = s

	return e
}

func (e *AudioElement) Translate(a AudioTranslate) *AudioElement {
	e.attributes["translate"] = a

	return e
}

func (e *AudioElement) Writingsuggestions(a AudioWritingsuggestions) *AudioElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *AudioElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<audio")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</audio>")

	_, err := io.WriteString(w, sb.String())
	return err
}
