// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type AudioElement struct {
	children []htemel.Node
}

// Audio creates a tag <audio> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: An audio element represents a sound or audio stream.
func Audio(children ...htemel.Node) *AudioElement {
	node := &AudioElement{
		children: children,
	}

	return node
}

func AudioIf(condition bool, children ...htemel.Node) *AudioElement {
	if condition {
		return Audio(children...)
	}

	return nil
}

func (e *AudioElement) Render(w io.Writer) error {
	if _, err := w.Write([]byte("<audio")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</audio>")); err != nil {
		return err
	}

	return nil
}
