// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type ButtonElement struct {
	children []htemel.Node
	skipRender bool
}

// Button creates a tag <button> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The button element represents a button labeled by its contents.
func Button(children ...htemel.Node) *ButtonElement {
	node := &ButtonElement{
		children: children,
	}

	return node
}

func ButtonIf(condition bool, children ...htemel.Node) *ButtonElement {
	if condition {
		return Button(children...)
	}

	return &ButtonElement{
		skipRender: true,
	}
}

func (e *ButtonElement) Autocapitalize() *ButtonElement {
	return e
}

func (e *ButtonElement) Autocorrect() *ButtonElement {
	return e
}

func (e *ButtonElement) Autofocus() *ButtonElement {
	return e
}

func (e *ButtonElement) Class() *ButtonElement {
	return e
}

func (e *ButtonElement) Contenteditable() *ButtonElement {
	return e
}

func (e *ButtonElement) Id() *ButtonElement {
	return e
}

func (e *ButtonElement) Slot() *ButtonElement {
	return e
}

func (e *ButtonElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<button")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</button>")); err != nil {
		return err
	}

	return nil
}
