// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"golang.org/x/net/html"
)

type ColElement struct {
	attributes colAttrs

	skipRender bool
}

// Col creates a tag <col> instance and returns it for further modification.
//
// Spec Description: If a col element has a parent and that is a colgroup element that itself has a parent that is a table element, then the col element represents one or more columns in the column group represented by that colgroup.
func Col() *ColElement {
	node := &ColElement{

		attributes: make(colAttrs),
	}

	return node
}

func ColIf(condition bool) *ColElement {
	if condition {
		return Col()
	}

	return &ColElement{

		attributes: make(colAttrs),
		skipRender: true,
	}
}

type ColAutocapitalize string

const (
	ColAutocapitalizeCharacters ColAutocapitalize = "characters"
	ColAutocapitalizeNone       ColAutocapitalize = "none"
	ColAutocapitalizeOff        ColAutocapitalize = "off"
	ColAutocapitalizeOn         ColAutocapitalize = "on"
	ColAutocapitalizeSentences  ColAutocapitalize = "sentences"
	ColAutocapitalizeWords      ColAutocapitalize = "words"
)

type ColAutocorrect string

const (
	ColAutocorrectOff   ColAutocorrect = "off"
	ColAutocorrectOn    ColAutocorrect = "on"
	ColAutocorrectEmpty ColAutocorrect = ""
)

type ColContenteditable string

const (
	ColContenteditableFalse         ColContenteditable = "false"
	ColContenteditablePlaintextOnly ColContenteditable = "plaintext-only"
	ColContenteditableTrue          ColContenteditable = "true"
	ColContenteditableEmpty         ColContenteditable = ""
)

type ColDir string

const (
	ColDirLtr  ColDir = "ltr"
	ColDirRtl  ColDir = "rtl"
	ColDirAuto ColDir = "auto"
)

type ColDraggable string

const (
	ColDraggableFalse ColDraggable = "false"
	ColDraggableTrue  ColDraggable = "true"
)

type ColEnterkeyhint string

const (
	ColEnterkeyhintPrevious ColEnterkeyhint = "previous"
	ColEnterkeyhintSearch   ColEnterkeyhint = "search"
	ColEnterkeyhintSend     ColEnterkeyhint = "send"
	ColEnterkeyhintDone     ColEnterkeyhint = "done"
	ColEnterkeyhintEnter    ColEnterkeyhint = "enter"
	ColEnterkeyhintGo       ColEnterkeyhint = "go"
	ColEnterkeyhintNext     ColEnterkeyhint = "next"
)

type ColHidden string

const (
	ColHiddenHidden     ColHidden = "hidden"
	ColHiddenUntilFound ColHidden = "until-found"
	ColHiddenEmpty      ColHidden = ""
)

type ColInputmode string

const (
	ColInputmodeUrl     ColInputmode = "url"
	ColInputmodeDecimal ColInputmode = "decimal"
	ColInputmodeEmail   ColInputmode = "email"
	ColInputmodeNone    ColInputmode = "none"
	ColInputmodeNumeric ColInputmode = "numeric"
	ColInputmodeSearch  ColInputmode = "search"
	ColInputmodeTel     ColInputmode = "tel"
	ColInputmodeText    ColInputmode = "text"
)

type ColSpellcheck string

const (
	ColSpellcheckFalse ColSpellcheck = "false"
	ColSpellcheckTrue  ColSpellcheck = "true"
	ColSpellcheckEmpty ColSpellcheck = ""
)

type ColTranslate string

const (
	ColTranslateYes   ColTranslate = "yes"
	ColTranslateNo    ColTranslate = "no"
	ColTranslateEmpty ColTranslate = ""
)

type ColWritingsuggestions string

const (
	ColWritingsuggestionsFalse ColWritingsuggestions = "false"
	ColWritingsuggestionsTrue  ColWritingsuggestions = "true"
	ColWritingsuggestionsEmpty ColWritingsuggestions = ""
)

type colAttrs map[string]any

func (e *ColElement) Span(i int) *ColElement {
	e.attributes["span"] = i

	return e
}

func (e *ColElement) AriaUnsafe(name string, s string) *ColElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ColElement) Aria(name string, s string) *ColElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *ColElement) Autocapitalize(a ColAutocapitalize) *ColElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *ColElement) Autocorrect(a ColAutocorrect) *ColElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *ColElement) Autofocus(b bool) *ColElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *ColElement) Class(s ...string) *ColElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *ColElement) Contenteditable(a ColContenteditable) *ColElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *ColElement) DataUnsafe(name string, s string) *ColElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ColElement) Data(name string, s string) *ColElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *ColElement) Dir(a ColDir) *ColElement {
	e.attributes["dir"] = a

	return e
}

func (e *ColElement) Draggable(a ColDraggable) *ColElement {
	e.attributes["draggable"] = a

	return e
}

func (e *ColElement) Enterkeyhint(a ColEnterkeyhint) *ColElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *ColElement) Hidden(a ColHidden) *ColElement {
	e.attributes["hidden"] = a

	return e
}

func (e *ColElement) Id(s string) *ColElement {
	e.attributes["id"] = s

	return e
}

func (e *ColElement) Inert(b bool) *ColElement {
	e.attributes["inert"] = b

	return e
}

func (e *ColElement) Inputmode(a ColInputmode) *ColElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *ColElement) Itemid(s string) *ColElement {
	e.attributes["itemid"] = s

	return e
}

func (e *ColElement) Itemprop(s ...string) *ColElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *ColElement) Itemref(s ...string) *ColElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *ColElement) Itemscope(b bool) *ColElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *ColElement) Itemtype(s ...string) *ColElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *ColElement) Lang(s string) *ColElement {
	e.attributes["lang"] = s

	return e
}

func (e *ColElement) Nonce(s string) *ColElement {
	e.attributes["nonce"] = s

	return e
}

func (e *ColElement) Popover(s string) *ColElement {
	e.attributes["popover"] = s

	return e
}

func (e *ColElement) Slot(s string) *ColElement {
	e.attributes["slot"] = s

	return e
}

func (e *ColElement) Spellcheck(a ColSpellcheck) *ColElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *ColElement) Style(s string) *ColElement {
	e.attributes["style"] = s

	return e
}

func (e *ColElement) Tabindex(i int) *ColElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *ColElement) Title(s string) *ColElement {
	e.attributes["title"] = s

	return e
}

func (e *ColElement) Translate(a ColTranslate) *ColElement {
	e.attributes["translate"] = a

	return e
}

func (e *ColElement) Writingsuggestions(a ColWritingsuggestions) *ColElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *ColElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<col")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	return nil
}
