// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/go-htemel/htemel"
	"golang.org/x/net/html"
)

type ColgroupElement struct {
	attributes colgroupAttrs
	children   []htemel.Node
	skipRender bool
}

// Colgroup creates a tag <colgroup> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
func Colgroup(children ...htemel.Node) *ColgroupElement {
	node := &ColgroupElement{
		children:   children,
		attributes: make(colgroupAttrs),
	}

	return node
}

func ColgroupIf(condition bool, children ...htemel.Node) *ColgroupElement {
	if condition {
		return Colgroup(children...)
	}

	return &ColgroupElement{
		children:   children,
		attributes: make(colgroupAttrs),
		skipRender: true,
	}
}

func ColgroupTernary(condition bool, true htemel.Node, false htemel.Node) *ColgroupElement {
	if condition {
		return Colgroup(true)
	}
	return Colgroup(false)
}

// Children appends children to this element.
func (e *ColgroupElement) Children(children ...htemel.Node) *ColgroupElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *ColgroupElement) With(fn func(*ColgroupElement)) *ColgroupElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *ColgroupElement) Text(text string) *ColgroupElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *ColgroupElement) Textf(format string, args ...any) *ColgroupElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// If conditionally adds a child node to the element if the condition is true, otherwise it is a no-op.
func (e *ColgroupElement) If(cond bool, child htemel.Node) *ColgroupElement {
	if cond {
		return e.Children(child)
	}
	return e
}

func (e *ColgroupElement) IfElse(cond bool, then, els htemel.Node) *ColgroupElement {
	if cond {
		e.Children(then)
	} else {
		e.Children(els)
	}
	return e
}

// IfThen conditionally calls the given function with the element if the condition is true, otherwise it is a no-op.
func (e *ColgroupElement) IfThen(cond bool, fn func(*ColgroupElement)) *ColgroupElement {
	if cond {
		fn(e)
	}
	return e
}

// AddClass appends a class to the element.
func (e *ColgroupElement) AddClass(classes ...string) *ColgroupElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *ColgroupElement) ToggleClass(class string, enable bool) *ColgroupElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type ColgroupAutocapitalize string

const (
	ColgroupAutocapitalizeWords      ColgroupAutocapitalize = "words"
	ColgroupAutocapitalizeCharacters ColgroupAutocapitalize = "characters"
	ColgroupAutocapitalizeNone       ColgroupAutocapitalize = "none"
	ColgroupAutocapitalizeOff        ColgroupAutocapitalize = "off"
	ColgroupAutocapitalizeOn         ColgroupAutocapitalize = "on"
	ColgroupAutocapitalizeSentences  ColgroupAutocapitalize = "sentences"
)

type ColgroupAutocorrect string

const (
	ColgroupAutocorrectOff   ColgroupAutocorrect = "off"
	ColgroupAutocorrectOn    ColgroupAutocorrect = "on"
	ColgroupAutocorrectEmpty ColgroupAutocorrect = ""
)

type ColgroupContenteditable string

const (
	ColgroupContenteditableFalse         ColgroupContenteditable = "false"
	ColgroupContenteditablePlaintextOnly ColgroupContenteditable = "plaintext-only"
	ColgroupContenteditableTrue          ColgroupContenteditable = "true"
	ColgroupContenteditableEmpty         ColgroupContenteditable = ""
)

type ColgroupDir string

const (
	ColgroupDirAuto ColgroupDir = "auto"
	ColgroupDirLtr  ColgroupDir = "ltr"
	ColgroupDirRtl  ColgroupDir = "rtl"
)

type ColgroupDraggable string

const (
	ColgroupDraggableTrue  ColgroupDraggable = "true"
	ColgroupDraggableFalse ColgroupDraggable = "false"
)

type ColgroupEnterkeyhint string

const (
	ColgroupEnterkeyhintGo       ColgroupEnterkeyhint = "go"
	ColgroupEnterkeyhintNext     ColgroupEnterkeyhint = "next"
	ColgroupEnterkeyhintPrevious ColgroupEnterkeyhint = "previous"
	ColgroupEnterkeyhintSearch   ColgroupEnterkeyhint = "search"
	ColgroupEnterkeyhintSend     ColgroupEnterkeyhint = "send"
	ColgroupEnterkeyhintDone     ColgroupEnterkeyhint = "done"
	ColgroupEnterkeyhintEnter    ColgroupEnterkeyhint = "enter"
)

type ColgroupHidden string

const (
	ColgroupHiddenHidden     ColgroupHidden = "hidden"
	ColgroupHiddenUntilFound ColgroupHidden = "until-found"
	ColgroupHiddenEmpty      ColgroupHidden = ""
)

type ColgroupInputmode string

const (
	ColgroupInputmodeSearch  ColgroupInputmode = "search"
	ColgroupInputmodeTel     ColgroupInputmode = "tel"
	ColgroupInputmodeText    ColgroupInputmode = "text"
	ColgroupInputmodeUrl     ColgroupInputmode = "url"
	ColgroupInputmodeDecimal ColgroupInputmode = "decimal"
	ColgroupInputmodeEmail   ColgroupInputmode = "email"
	ColgroupInputmodeNone    ColgroupInputmode = "none"
	ColgroupInputmodeNumeric ColgroupInputmode = "numeric"
)

type ColgroupSpellcheck string

const (
	ColgroupSpellcheckFalse ColgroupSpellcheck = "false"
	ColgroupSpellcheckTrue  ColgroupSpellcheck = "true"
	ColgroupSpellcheckEmpty ColgroupSpellcheck = ""
)

type ColgroupTranslate string

const (
	ColgroupTranslateNo    ColgroupTranslate = "no"
	ColgroupTranslateYes   ColgroupTranslate = "yes"
	ColgroupTranslateEmpty ColgroupTranslate = ""
)

type ColgroupWritingsuggestions string

const (
	ColgroupWritingsuggestionsTrue  ColgroupWritingsuggestions = "true"
	ColgroupWritingsuggestionsFalse ColgroupWritingsuggestions = "false"
	ColgroupWritingsuggestionsEmpty ColgroupWritingsuggestions = ""
)

type colgroupAttrs map[string]any

func (e *ColgroupElement) Span(i int) *ColgroupElement {
	e.attributes["span"] = i

	return e
}

func (e *ColgroupElement) AriaUnsafe(name string, s string) *ColgroupElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ColgroupElement) Aria(name string, s string) *ColgroupElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *ColgroupElement) Autocapitalize(a ColgroupAutocapitalize) *ColgroupElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *ColgroupElement) Autocorrect(a ColgroupAutocorrect) *ColgroupElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *ColgroupElement) Autofocus(b bool) *ColgroupElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *ColgroupElement) Class(s ...string) *ColgroupElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *ColgroupElement) Contenteditable(a ColgroupContenteditable) *ColgroupElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *ColgroupElement) DataUnsafe(name string, s string) *ColgroupElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ColgroupElement) Data(name string, s string) *ColgroupElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *ColgroupElement) Dir(a ColgroupDir) *ColgroupElement {
	e.attributes["dir"] = a

	return e
}

func (e *ColgroupElement) Draggable(a ColgroupDraggable) *ColgroupElement {
	e.attributes["draggable"] = a

	return e
}

func (e *ColgroupElement) Enterkeyhint(a ColgroupEnterkeyhint) *ColgroupElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *ColgroupElement) Hidden(a ColgroupHidden) *ColgroupElement {
	e.attributes["hidden"] = a

	return e
}

func (e *ColgroupElement) Id(s string) *ColgroupElement {
	e.attributes["id"] = s

	return e
}

func (e *ColgroupElement) Inert(b bool) *ColgroupElement {
	e.attributes["inert"] = b

	return e
}

func (e *ColgroupElement) Inputmode(a ColgroupInputmode) *ColgroupElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *ColgroupElement) Itemid(s string) *ColgroupElement {
	e.attributes["itemid"] = s

	return e
}

func (e *ColgroupElement) Itemprop(s ...string) *ColgroupElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *ColgroupElement) Itemref(s ...string) *ColgroupElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *ColgroupElement) Itemscope(b bool) *ColgroupElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *ColgroupElement) Itemtype(s ...string) *ColgroupElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *ColgroupElement) Lang(s string) *ColgroupElement {
	e.attributes["lang"] = s

	return e
}

func (e *ColgroupElement) Nonce(s string) *ColgroupElement {
	e.attributes["nonce"] = s

	return e
}

func (e *ColgroupElement) Popover(s string) *ColgroupElement {
	e.attributes["popover"] = s

	return e
}

func (e *ColgroupElement) Role(s string) *ColgroupElement {
	e.attributes["role"] = s

	return e
}

func (e *ColgroupElement) Slot(s string) *ColgroupElement {
	e.attributes["slot"] = s

	return e
}

func (e *ColgroupElement) Spellcheck(a ColgroupSpellcheck) *ColgroupElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *ColgroupElement) Style(s string) *ColgroupElement {
	e.attributes["style"] = s

	return e
}

func (e *ColgroupElement) Tabindex(i int) *ColgroupElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *ColgroupElement) Title(s string) *ColgroupElement {
	e.attributes["title"] = s

	return e
}

func (e *ColgroupElement) Translate(a ColgroupTranslate) *ColgroupElement {
	e.attributes["translate"] = a

	return e
}

func (e *ColgroupElement) Writingsuggestions(a ColgroupWritingsuggestions) *ColgroupElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *ColgroupElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<colgroup")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</colgroup>")

	_, err := io.WriteString(w, sb.String())
	return err
}
