// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type DetailsElement struct {
	attributes detailsAttrs
	children   []htemel.Node
	skipRender bool
}

// Details creates a tag <details> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The details element represents a disclosure widget from which the user can obtain additional information or controls.
func Details(children ...htemel.Node) *DetailsElement {
	node := &DetailsElement{
		children:   children,
		attributes: make(detailsAttrs),
	}

	return node
}

func DetailsIf(condition bool, children ...htemel.Node) *DetailsElement {
	if condition {
		return Details(children...)
	}

	return &DetailsElement{
		children:   children,
		attributes: make(detailsAttrs),
		skipRender: true,
	}
}

func DetailsTernary(condition bool, true htemel.Node, false htemel.Node) *DetailsElement {
	if condition {
		return Details(true)
	}
	return Details(false)
}

// Children appends children to this element.
func (e *DetailsElement) Children(children ...htemel.Node) *DetailsElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *DetailsElement) With(fn func(*DetailsElement)) *DetailsElement {
	fn(e)
	return e
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *DetailsElement) Textf(format string, args ...any) *DetailsElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *DetailsElement) AddClass(classes ...string) *DetailsElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *DetailsElement) ToggleClass(class string, enable bool) *DetailsElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type DetailsAutocapitalize string

const (
	DetailsAutocapitalizeCharacters DetailsAutocapitalize = "characters"
	DetailsAutocapitalizeNone       DetailsAutocapitalize = "none"
	DetailsAutocapitalizeOff        DetailsAutocapitalize = "off"
	DetailsAutocapitalizeOn         DetailsAutocapitalize = "on"
	DetailsAutocapitalizeSentences  DetailsAutocapitalize = "sentences"
	DetailsAutocapitalizeWords      DetailsAutocapitalize = "words"
)

type DetailsAutocorrect string

const (
	DetailsAutocorrectOff   DetailsAutocorrect = "off"
	DetailsAutocorrectOn    DetailsAutocorrect = "on"
	DetailsAutocorrectEmpty DetailsAutocorrect = ""
)

type DetailsContenteditable string

const (
	DetailsContenteditableFalse         DetailsContenteditable = "false"
	DetailsContenteditablePlaintextOnly DetailsContenteditable = "plaintext-only"
	DetailsContenteditableTrue          DetailsContenteditable = "true"
	DetailsContenteditableEmpty         DetailsContenteditable = ""
)

type DetailsDir string

const (
	DetailsDirAuto DetailsDir = "auto"
	DetailsDirLtr  DetailsDir = "ltr"
	DetailsDirRtl  DetailsDir = "rtl"
)

type DetailsDraggable string

const (
	DetailsDraggableFalse DetailsDraggable = "false"
	DetailsDraggableTrue  DetailsDraggable = "true"
)

type DetailsEnterkeyhint string

const (
	DetailsEnterkeyhintPrevious DetailsEnterkeyhint = "previous"
	DetailsEnterkeyhintSearch   DetailsEnterkeyhint = "search"
	DetailsEnterkeyhintSend     DetailsEnterkeyhint = "send"
	DetailsEnterkeyhintDone     DetailsEnterkeyhint = "done"
	DetailsEnterkeyhintEnter    DetailsEnterkeyhint = "enter"
	DetailsEnterkeyhintGo       DetailsEnterkeyhint = "go"
	DetailsEnterkeyhintNext     DetailsEnterkeyhint = "next"
)

type DetailsHidden string

const (
	DetailsHiddenHidden     DetailsHidden = "hidden"
	DetailsHiddenUntilFound DetailsHidden = "until-found"
	DetailsHiddenEmpty      DetailsHidden = ""
)

type DetailsInputmode string

const (
	DetailsInputmodeUrl     DetailsInputmode = "url"
	DetailsInputmodeDecimal DetailsInputmode = "decimal"
	DetailsInputmodeEmail   DetailsInputmode = "email"
	DetailsInputmodeNone    DetailsInputmode = "none"
	DetailsInputmodeNumeric DetailsInputmode = "numeric"
	DetailsInputmodeSearch  DetailsInputmode = "search"
	DetailsInputmodeTel     DetailsInputmode = "tel"
	DetailsInputmodeText    DetailsInputmode = "text"
)

type DetailsSpellcheck string

const (
	DetailsSpellcheckFalse DetailsSpellcheck = "false"
	DetailsSpellcheckTrue  DetailsSpellcheck = "true"
	DetailsSpellcheckEmpty DetailsSpellcheck = ""
)

type DetailsTranslate string

const (
	DetailsTranslateNo    DetailsTranslate = "no"
	DetailsTranslateYes   DetailsTranslate = "yes"
	DetailsTranslateEmpty DetailsTranslate = ""
)

type DetailsWritingsuggestions string

const (
	DetailsWritingsuggestionsFalse DetailsWritingsuggestions = "false"
	DetailsWritingsuggestionsTrue  DetailsWritingsuggestions = "true"
	DetailsWritingsuggestionsEmpty DetailsWritingsuggestions = ""
)

type detailsAttrs map[string]any

func (e *DetailsElement) Name(s string) *DetailsElement {
	e.attributes["name"] = s

	return e
}

func (e *DetailsElement) Open(b bool) *DetailsElement {
	e.attributes["open"] = b

	return e
}

func (e *DetailsElement) AriaUnsafe(name string, s string) *DetailsElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DetailsElement) Aria(name string, s string) *DetailsElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *DetailsElement) Autocapitalize(a DetailsAutocapitalize) *DetailsElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *DetailsElement) Autocorrect(a DetailsAutocorrect) *DetailsElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *DetailsElement) Autofocus(b bool) *DetailsElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *DetailsElement) Class(s ...string) *DetailsElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *DetailsElement) Contenteditable(a DetailsContenteditable) *DetailsElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *DetailsElement) DataUnsafe(name string, s string) *DetailsElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DetailsElement) Data(name string, s string) *DetailsElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *DetailsElement) Dir(a DetailsDir) *DetailsElement {
	e.attributes["dir"] = a

	return e
}

func (e *DetailsElement) Draggable(a DetailsDraggable) *DetailsElement {
	e.attributes["draggable"] = a

	return e
}

func (e *DetailsElement) Enterkeyhint(a DetailsEnterkeyhint) *DetailsElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *DetailsElement) Hidden(a DetailsHidden) *DetailsElement {
	e.attributes["hidden"] = a

	return e
}

func (e *DetailsElement) Id(s string) *DetailsElement {
	e.attributes["id"] = s

	return e
}

func (e *DetailsElement) Inert(b bool) *DetailsElement {
	e.attributes["inert"] = b

	return e
}

func (e *DetailsElement) Inputmode(a DetailsInputmode) *DetailsElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *DetailsElement) Itemid(s string) *DetailsElement {
	e.attributes["itemid"] = s

	return e
}

func (e *DetailsElement) Itemprop(s ...string) *DetailsElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *DetailsElement) Itemref(s ...string) *DetailsElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *DetailsElement) Itemscope(b bool) *DetailsElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *DetailsElement) Itemtype(s ...string) *DetailsElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *DetailsElement) Lang(s string) *DetailsElement {
	e.attributes["lang"] = s

	return e
}

func (e *DetailsElement) Nonce(s string) *DetailsElement {
	e.attributes["nonce"] = s

	return e
}

func (e *DetailsElement) Popover(s string) *DetailsElement {
	e.attributes["popover"] = s

	return e
}

func (e *DetailsElement) Role(s string) *DetailsElement {
	e.attributes["role"] = s

	return e
}

func (e *DetailsElement) Slot(s string) *DetailsElement {
	e.attributes["slot"] = s

	return e
}

func (e *DetailsElement) Spellcheck(a DetailsSpellcheck) *DetailsElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *DetailsElement) Style(s string) *DetailsElement {
	e.attributes["style"] = s

	return e
}

func (e *DetailsElement) Tabindex(i int) *DetailsElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *DetailsElement) Title(s string) *DetailsElement {
	e.attributes["title"] = s

	return e
}

func (e *DetailsElement) Translate(a DetailsTranslate) *DetailsElement {
	e.attributes["translate"] = a

	return e
}

func (e *DetailsElement) Writingsuggestions(a DetailsWritingsuggestions) *DetailsElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *DetailsElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<details")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</details>")); err != nil {
		return err
	}

	return nil
}
