// Code generated by htemel. DO NOT EDIT.
package html

import (
  "fmt"
  "github.com/derekmwright/htemel"
  "golang.org/x/net/html"
  "io"
)

type DivElement struct {
	attributes divAttrs
	children []htemel.Node
	skipRender bool
}

// Div creates a tag <div> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The div element has no special meaning at all. It represents its children. It can be used with the class, lang, and title attributes to mark up semantics common to a group of consecutive elements. It can also be used in a dl element, wrapping groups of dt and dd elements.
func Div(children ...htemel.Node) *DivElement {
	node := &DivElement{
		children: children,
	}

	return node
}

func DivIf(condition bool, children ...htemel.Node) *DivElement {
	if condition {
		return Div(children...)
	}

	return &DivElement{
		skipRender: true,
	}
}

type DivAutocapitalizeAttrEnum string

const (
	DivAutocapitalizeAttrEnumSentences DivAutocapitalizeAttrEnum = "sentences"
	DivAutocapitalizeAttrEnumWords DivAutocapitalizeAttrEnum = "words"
	DivAutocapitalizeAttrEnumCharacters DivAutocapitalizeAttrEnum = "characters"
	DivAutocapitalizeAttrEnumNone DivAutocapitalizeAttrEnum = "none"
	DivAutocapitalizeAttrEnumOff DivAutocapitalizeAttrEnum = "off"
	DivAutocapitalizeAttrEnumOn DivAutocapitalizeAttrEnum = "on"
)

type DivAutocorrectAttrEnum string

const (
	DivAutocorrectAttrEnumOff DivAutocorrectAttrEnum = "off"
	DivAutocorrectAttrEnumOn DivAutocorrectAttrEnum = "on"
)

type DivContenteditableAttrEnum string

const (
	DivContenteditableAttrEnumFalse DivContenteditableAttrEnum = "false"
	DivContenteditableAttrEnumPlaintextOnly DivContenteditableAttrEnum = "plaintext-only"
	DivContenteditableAttrEnumTrue DivContenteditableAttrEnum = "true"
)

type divAttrs map[string]any

func (e *DivElement) Autocapitalize(a DivAutocapitalizeAttrEnum) *DivElement {
	e.attributes["autocapitalize"] = a
	
	return e
}

func (e *DivElement) Autocorrect(a DivAutocorrectAttrEnum) *DivElement {
	e.attributes["autocorrect"] = a
	
	return e
}

func (e *DivElement) Class(s ...string) *DivElement {
	e.attributes["class"] = strings.Join(s, " ")
	
	return e
}

func (e *DivElement) Contenteditable(a DivContenteditableAttrEnum) *DivElement {
	e.attributes["contenteditable"] = a
	
	return e
}

func (e *DivElement) Id(s string) *DivElement {
	e.attributes["id"] = s
	
	return e
}

func (e *DivElement) Slot(s string) *DivElement {
	e.attributes["slot"] = s
	
	return e
}

func (e *DivElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<div")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 0
	for key, v := range e.attributes {
		w.Write([]byte(key + "="))
		w.Write([]byte(html.EscapeString(fmt.Sprintf("'%v'", v))))
		if i < c {
			w.Write([]byte(" "))
		}
		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</div>")); err != nil {
		return err
	}

	return nil
}
