// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type DivElement struct {
	attributes divAttrs
	children   []htemel.Node
	skipRender bool
}

// Div creates a tag <div> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The div element has no special meaning at all. It represents its children. It can be used with the class, lang, and title attributes to mark up semantics common to a group of consecutive elements. It can also be used in a dl element, wrapping groups of dt and dd elements.
func Div(children ...htemel.Node) *DivElement {
	node := &DivElement{
		children:   children,
		attributes: make(divAttrs),
	}

	return node
}

func DivIf(condition bool, children ...htemel.Node) *DivElement {
	if condition {
		return Div(children...)
	}

	return &DivElement{
		children:   children,
		attributes: make(divAttrs),
		skipRender: true,
	}
}

func DivTernary(condition bool, true htemel.Node, false htemel.Node) *DivElement {
	if condition {
		return Div(true)
	}

	return Div(false)
}

type DivAutocapitalize string

const (
	DivAutocapitalizeCharacters DivAutocapitalize = "characters"
	DivAutocapitalizeNone       DivAutocapitalize = "none"
	DivAutocapitalizeOff        DivAutocapitalize = "off"
	DivAutocapitalizeOn         DivAutocapitalize = "on"
	DivAutocapitalizeSentences  DivAutocapitalize = "sentences"
	DivAutocapitalizeWords      DivAutocapitalize = "words"
)

type DivAutocorrect string

const (
	DivAutocorrectOff   DivAutocorrect = "off"
	DivAutocorrectOn    DivAutocorrect = "on"
	DivAutocorrectEmpty DivAutocorrect = ""
)

type DivContenteditable string

const (
	DivContenteditableFalse         DivContenteditable = "false"
	DivContenteditablePlaintextOnly DivContenteditable = "plaintext-only"
	DivContenteditableTrue          DivContenteditable = "true"
	DivContenteditableEmpty         DivContenteditable = ""
)

type DivDir string

const (
	DivDirAuto DivDir = "auto"
	DivDirLtr  DivDir = "ltr"
	DivDirRtl  DivDir = "rtl"
)

type DivDraggable string

const (
	DivDraggableFalse DivDraggable = "false"
	DivDraggableTrue  DivDraggable = "true"
)

type DivEnterkeyhint string

const (
	DivEnterkeyhintDone     DivEnterkeyhint = "done"
	DivEnterkeyhintEnter    DivEnterkeyhint = "enter"
	DivEnterkeyhintGo       DivEnterkeyhint = "go"
	DivEnterkeyhintNext     DivEnterkeyhint = "next"
	DivEnterkeyhintPrevious DivEnterkeyhint = "previous"
	DivEnterkeyhintSearch   DivEnterkeyhint = "search"
	DivEnterkeyhintSend     DivEnterkeyhint = "send"
)

type DivHidden string

const (
	DivHiddenHidden     DivHidden = "hidden"
	DivHiddenUntilFound DivHidden = "until-found"
	DivHiddenEmpty      DivHidden = ""
)

type DivInputmode string

const (
	DivInputmodeEmail   DivInputmode = "email"
	DivInputmodeNone    DivInputmode = "none"
	DivInputmodeNumeric DivInputmode = "numeric"
	DivInputmodeSearch  DivInputmode = "search"
	DivInputmodeTel     DivInputmode = "tel"
	DivInputmodeText    DivInputmode = "text"
	DivInputmodeUrl     DivInputmode = "url"
	DivInputmodeDecimal DivInputmode = "decimal"
)

type DivSpellcheck string

const (
	DivSpellcheckFalse DivSpellcheck = "false"
	DivSpellcheckTrue  DivSpellcheck = "true"
	DivSpellcheckEmpty DivSpellcheck = ""
)

type DivTranslate string

const (
	DivTranslateYes   DivTranslate = "yes"
	DivTranslateNo    DivTranslate = "no"
	DivTranslateEmpty DivTranslate = ""
)

type DivWritingsuggestions string

const (
	DivWritingsuggestionsFalse DivWritingsuggestions = "false"
	DivWritingsuggestionsTrue  DivWritingsuggestions = "true"
	DivWritingsuggestionsEmpty DivWritingsuggestions = ""
)

type divAttrs map[string]any

func (e *DivElement) AriaUnsafe(name string, s string) *DivElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DivElement) Aria(name string, s string) *DivElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *DivElement) Autocapitalize(a DivAutocapitalize) *DivElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *DivElement) Autocorrect(a DivAutocorrect) *DivElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *DivElement) Autofocus(b bool) *DivElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *DivElement) Class(s ...string) *DivElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *DivElement) Contenteditable(a DivContenteditable) *DivElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *DivElement) DataUnsafe(name string, s string) *DivElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DivElement) Data(name string, s string) *DivElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *DivElement) Dir(a DivDir) *DivElement {
	e.attributes["dir"] = a

	return e
}

func (e *DivElement) Draggable(a DivDraggable) *DivElement {
	e.attributes["draggable"] = a

	return e
}

func (e *DivElement) Enterkeyhint(a DivEnterkeyhint) *DivElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *DivElement) Hidden(a DivHidden) *DivElement {
	e.attributes["hidden"] = a

	return e
}

func (e *DivElement) Id(s string) *DivElement {
	e.attributes["id"] = s

	return e
}

func (e *DivElement) Inert(b bool) *DivElement {
	e.attributes["inert"] = b

	return e
}

func (e *DivElement) Inputmode(a DivInputmode) *DivElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *DivElement) Itemid(s string) *DivElement {
	e.attributes["itemid"] = s

	return e
}

func (e *DivElement) Itemprop(s ...string) *DivElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *DivElement) Itemref(s ...string) *DivElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *DivElement) Itemscope(b bool) *DivElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *DivElement) Itemtype(s ...string) *DivElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *DivElement) Lang(s string) *DivElement {
	e.attributes["lang"] = s

	return e
}

func (e *DivElement) Nonce(s string) *DivElement {
	e.attributes["nonce"] = s

	return e
}

func (e *DivElement) Popover(s string) *DivElement {
	e.attributes["popover"] = s

	return e
}

func (e *DivElement) Slot(s string) *DivElement {
	e.attributes["slot"] = s

	return e
}

func (e *DivElement) Spellcheck(a DivSpellcheck) *DivElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *DivElement) Style(s string) *DivElement {
	e.attributes["style"] = s

	return e
}

func (e *DivElement) Tabindex(i int) *DivElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *DivElement) Title(s string) *DivElement {
	e.attributes["title"] = s

	return e
}

func (e *DivElement) Translate(a DivTranslate) *DivElement {
	e.attributes["translate"] = a

	return e
}

func (e *DivElement) Writingsuggestions(a DivWritingsuggestions) *DivElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *DivElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<div")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</div>")); err != nil {
		return err
	}

	return nil
}
