// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/go-htemel/htemel"
	"golang.org/x/net/html"
)

type DlElement struct {
	attributes dlAttrs
	children   []htemel.Node
	skipRender bool
}

// Dl creates a tag <dl> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The dl element represents an association list consisting of zero or more name-value groups (a description list). A name-value group consists of one or more names (dt elements, possibly as children of a div element child) followed by one or more values (dd elements, possibly as children of a div element child), ignoring any nodes other than dt and dd element children, and dt and dd elements that are children of div element children. Within a single dl element, there should not be more than one dt element for each name.
func Dl(children ...htemel.Node) *DlElement {
	node := &DlElement{
		children:   children,
		attributes: make(dlAttrs),
	}

	return node
}

func DlIf(condition bool, children ...htemel.Node) *DlElement {
	if condition {
		return Dl(children...)
	}

	return &DlElement{
		children:   children,
		attributes: make(dlAttrs),
		skipRender: true,
	}
}

func DlTernary(condition bool, true htemel.Node, false htemel.Node) *DlElement {
	if condition {
		return Dl(true)
	}
	return Dl(false)
}

// Children appends children to this element.
func (e *DlElement) Children(children ...htemel.Node) *DlElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *DlElement) With(fn func(*DlElement)) *DlElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *DlElement) Text(text string) *DlElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *DlElement) Textf(format string, args ...any) *DlElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// If conditionally adds a child node to the element if the condition is true, otherwise it is a no-op.
func (e *DlElement) If(cond bool, child htemel.Node) *DlElement {
	if cond {
		return e.Children(child)
	}
	return e
}

func (e *DlElement) IfElse(cond bool, then, els htemel.Node) *DlElement {
	if cond {
		e.Children(then)
	} else {
		e.Children(els)
	}
	return e
}

// IfThen conditionally calls the given function with the element if the condition is true, otherwise it is a no-op.
func (e *DlElement) IfThen(cond bool, fn func(*DlElement)) *DlElement {
	if cond {
		fn(e)
	}
	return e
}

// AddClass appends a class to the element.
func (e *DlElement) AddClass(classes ...string) *DlElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *DlElement) ToggleClass(class string, enable bool) *DlElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type DlAutocapitalize string

const (
	DlAutocapitalizeCharacters DlAutocapitalize = "characters"
	DlAutocapitalizeNone       DlAutocapitalize = "none"
	DlAutocapitalizeOff        DlAutocapitalize = "off"
	DlAutocapitalizeOn         DlAutocapitalize = "on"
	DlAutocapitalizeSentences  DlAutocapitalize = "sentences"
	DlAutocapitalizeWords      DlAutocapitalize = "words"
)

type DlAutocorrect string

const (
	DlAutocorrectOff   DlAutocorrect = "off"
	DlAutocorrectOn    DlAutocorrect = "on"
	DlAutocorrectEmpty DlAutocorrect = ""
)

type DlContenteditable string

const (
	DlContenteditableFalse         DlContenteditable = "false"
	DlContenteditablePlaintextOnly DlContenteditable = "plaintext-only"
	DlContenteditableTrue          DlContenteditable = "true"
	DlContenteditableEmpty         DlContenteditable = ""
)

type DlDir string

const (
	DlDirAuto DlDir = "auto"
	DlDirLtr  DlDir = "ltr"
	DlDirRtl  DlDir = "rtl"
)

type DlDraggable string

const (
	DlDraggableFalse DlDraggable = "false"
	DlDraggableTrue  DlDraggable = "true"
)

type DlEnterkeyhint string

const (
	DlEnterkeyhintSearch   DlEnterkeyhint = "search"
	DlEnterkeyhintSend     DlEnterkeyhint = "send"
	DlEnterkeyhintDone     DlEnterkeyhint = "done"
	DlEnterkeyhintEnter    DlEnterkeyhint = "enter"
	DlEnterkeyhintGo       DlEnterkeyhint = "go"
	DlEnterkeyhintNext     DlEnterkeyhint = "next"
	DlEnterkeyhintPrevious DlEnterkeyhint = "previous"
)

type DlHidden string

const (
	DlHiddenHidden     DlHidden = "hidden"
	DlHiddenUntilFound DlHidden = "until-found"
	DlHiddenEmpty      DlHidden = ""
)

type DlInputmode string

const (
	DlInputmodeTel     DlInputmode = "tel"
	DlInputmodeText    DlInputmode = "text"
	DlInputmodeUrl     DlInputmode = "url"
	DlInputmodeDecimal DlInputmode = "decimal"
	DlInputmodeEmail   DlInputmode = "email"
	DlInputmodeNone    DlInputmode = "none"
	DlInputmodeNumeric DlInputmode = "numeric"
	DlInputmodeSearch  DlInputmode = "search"
)

type DlSpellcheck string

const (
	DlSpellcheckFalse DlSpellcheck = "false"
	DlSpellcheckTrue  DlSpellcheck = "true"
	DlSpellcheckEmpty DlSpellcheck = ""
)

type DlTranslate string

const (
	DlTranslateNo    DlTranslate = "no"
	DlTranslateYes   DlTranslate = "yes"
	DlTranslateEmpty DlTranslate = ""
)

type DlWritingsuggestions string

const (
	DlWritingsuggestionsFalse DlWritingsuggestions = "false"
	DlWritingsuggestionsTrue  DlWritingsuggestions = "true"
	DlWritingsuggestionsEmpty DlWritingsuggestions = ""
)

type dlAttrs map[string]any

func (e *DlElement) AriaUnsafe(name string, s string) *DlElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DlElement) Aria(name string, s string) *DlElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *DlElement) Autocapitalize(a DlAutocapitalize) *DlElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *DlElement) Autocorrect(a DlAutocorrect) *DlElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *DlElement) Autofocus(b bool) *DlElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *DlElement) Class(s ...string) *DlElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *DlElement) Contenteditable(a DlContenteditable) *DlElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *DlElement) DataUnsafe(name string, s string) *DlElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *DlElement) Data(name string, s string) *DlElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *DlElement) Dir(a DlDir) *DlElement {
	e.attributes["dir"] = a

	return e
}

func (e *DlElement) Draggable(a DlDraggable) *DlElement {
	e.attributes["draggable"] = a

	return e
}

func (e *DlElement) Enterkeyhint(a DlEnterkeyhint) *DlElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *DlElement) Hidden(a DlHidden) *DlElement {
	e.attributes["hidden"] = a

	return e
}

func (e *DlElement) Id(s string) *DlElement {
	e.attributes["id"] = s

	return e
}

func (e *DlElement) Inert(b bool) *DlElement {
	e.attributes["inert"] = b

	return e
}

func (e *DlElement) Inputmode(a DlInputmode) *DlElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *DlElement) Itemid(s string) *DlElement {
	e.attributes["itemid"] = s

	return e
}

func (e *DlElement) Itemprop(s ...string) *DlElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *DlElement) Itemref(s ...string) *DlElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *DlElement) Itemscope(b bool) *DlElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *DlElement) Itemtype(s ...string) *DlElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *DlElement) Lang(s string) *DlElement {
	e.attributes["lang"] = s

	return e
}

func (e *DlElement) Nonce(s string) *DlElement {
	e.attributes["nonce"] = s

	return e
}

func (e *DlElement) Popover(s string) *DlElement {
	e.attributes["popover"] = s

	return e
}

func (e *DlElement) Role(s string) *DlElement {
	e.attributes["role"] = s

	return e
}

func (e *DlElement) Slot(s string) *DlElement {
	e.attributes["slot"] = s

	return e
}

func (e *DlElement) Spellcheck(a DlSpellcheck) *DlElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *DlElement) Style(s string) *DlElement {
	e.attributes["style"] = s

	return e
}

func (e *DlElement) Tabindex(i int) *DlElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *DlElement) Title(s string) *DlElement {
	e.attributes["title"] = s

	return e
}

func (e *DlElement) Translate(a DlTranslate) *DlElement {
	e.attributes["translate"] = a

	return e
}

func (e *DlElement) Writingsuggestions(a DlWritingsuggestions) *DlElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *DlElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<dl")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</dl>")

	_, err := io.WriteString(w, sb.String())
	return err
}
