// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type DtElement struct {
	children []htemel.Node
}

// Dt creates a tag <dt> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The dt element represents the term, or name, part of a term-description group in a description list (dl element).
func Dt(children ...htemel.Node) *DtElement {
	node := &DtElement{
		children: children,
	}

	return node
}

func DtIf(condition bool, children ...htemel.Node) *DtElement {
	if condition {
		return Dt(children...)
	}

	return nil
}

func (e *DtElement) Render(w io.Writer) error {
	if _, err := w.Write([]byte("<dt")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</dt>")); err != nil {
		return err
	}

	return nil
}
