// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type FieldsetElement struct {
	children []htemel.Node
}

// Fieldset creates a tag <fieldset> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The fieldset element represents a set of form controls (or other content) grouped together, optionally with a caption. The caption is given by the first legend element that is a child of the fieldset element, if any. The remainder of the descendants form the group.
func Fieldset(children ...htemel.Node) *FieldsetElement {
	node := &FieldsetElement{
		children: children,
	}

	return node
}

func FieldsetIf(condition bool, children ...htemel.Node) *FieldsetElement {
	if condition {
		return Fieldset(children...)
	}

	return nil
}

func (e *FieldsetElement) Render(w io.Writer) error {
	if _, err := w.Write([]byte("<fieldset")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</fieldset>")); err != nil {
		return err
	}

	return nil
}
