// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type FigureElement struct {
	attributes figureAttrs
	children   []htemel.Node
	skipRender bool
}

// Figure creates a tag <figure> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The figure element represents some flow content, optionally with a caption, that is self-contained (like a complete sentence) and is typically referenced as a single unit from the main flow of the document.
func Figure(children ...htemel.Node) *FigureElement {
	node := &FigureElement{
		children:   children,
		attributes: make(figureAttrs),
	}

	return node
}

func FigureIf(condition bool, children ...htemel.Node) *FigureElement {
	if condition {
		return Figure(children...)
	}

	return &FigureElement{
		children:   children,
		attributes: make(figureAttrs),
		skipRender: true,
	}
}

func FigureTernary(condition bool, true htemel.Node, false htemel.Node) *FigureElement {
	if condition {
		return Figure(true)
	}

	return Figure(false)
}

// Children appends children to this element.
func (e *FigureElement) Children(children ...htemel.Node) *FigureElement {
	e.children = append(e.children, children...)

	return e
}

type FigureAutocapitalize string

const (
	FigureAutocapitalizeSentences  FigureAutocapitalize = "sentences"
	FigureAutocapitalizeWords      FigureAutocapitalize = "words"
	FigureAutocapitalizeCharacters FigureAutocapitalize = "characters"
	FigureAutocapitalizeNone       FigureAutocapitalize = "none"
	FigureAutocapitalizeOff        FigureAutocapitalize = "off"
	FigureAutocapitalizeOn         FigureAutocapitalize = "on"
)

type FigureAutocorrect string

const (
	FigureAutocorrectOff   FigureAutocorrect = "off"
	FigureAutocorrectOn    FigureAutocorrect = "on"
	FigureAutocorrectEmpty FigureAutocorrect = ""
)

type FigureContenteditable string

const (
	FigureContenteditableTrue          FigureContenteditable = "true"
	FigureContenteditableFalse         FigureContenteditable = "false"
	FigureContenteditablePlaintextOnly FigureContenteditable = "plaintext-only"
	FigureContenteditableEmpty         FigureContenteditable = ""
)

type FigureDir string

const (
	FigureDirAuto FigureDir = "auto"
	FigureDirLtr  FigureDir = "ltr"
	FigureDirRtl  FigureDir = "rtl"
)

type FigureDraggable string

const (
	FigureDraggableFalse FigureDraggable = "false"
	FigureDraggableTrue  FigureDraggable = "true"
)

type FigureEnterkeyhint string

const (
	FigureEnterkeyhintPrevious FigureEnterkeyhint = "previous"
	FigureEnterkeyhintSearch   FigureEnterkeyhint = "search"
	FigureEnterkeyhintSend     FigureEnterkeyhint = "send"
	FigureEnterkeyhintDone     FigureEnterkeyhint = "done"
	FigureEnterkeyhintEnter    FigureEnterkeyhint = "enter"
	FigureEnterkeyhintGo       FigureEnterkeyhint = "go"
	FigureEnterkeyhintNext     FigureEnterkeyhint = "next"
)

type FigureHidden string

const (
	FigureHiddenHidden     FigureHidden = "hidden"
	FigureHiddenUntilFound FigureHidden = "until-found"
	FigureHiddenEmpty      FigureHidden = ""
)

type FigureInputmode string

const (
	FigureInputmodeNone    FigureInputmode = "none"
	FigureInputmodeNumeric FigureInputmode = "numeric"
	FigureInputmodeSearch  FigureInputmode = "search"
	FigureInputmodeTel     FigureInputmode = "tel"
	FigureInputmodeText    FigureInputmode = "text"
	FigureInputmodeUrl     FigureInputmode = "url"
	FigureInputmodeDecimal FigureInputmode = "decimal"
	FigureInputmodeEmail   FigureInputmode = "email"
)

type FigureSpellcheck string

const (
	FigureSpellcheckFalse FigureSpellcheck = "false"
	FigureSpellcheckTrue  FigureSpellcheck = "true"
	FigureSpellcheckEmpty FigureSpellcheck = ""
)

type FigureTranslate string

const (
	FigureTranslateYes   FigureTranslate = "yes"
	FigureTranslateNo    FigureTranslate = "no"
	FigureTranslateEmpty FigureTranslate = ""
)

type FigureWritingsuggestions string

const (
	FigureWritingsuggestionsFalse FigureWritingsuggestions = "false"
	FigureWritingsuggestionsTrue  FigureWritingsuggestions = "true"
	FigureWritingsuggestionsEmpty FigureWritingsuggestions = ""
)

type figureAttrs map[string]any

func (e *FigureElement) AriaUnsafe(name string, s string) *FigureElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *FigureElement) Aria(name string, s string) *FigureElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *FigureElement) Autocapitalize(a FigureAutocapitalize) *FigureElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *FigureElement) Autocorrect(a FigureAutocorrect) *FigureElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *FigureElement) Autofocus(b bool) *FigureElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *FigureElement) Class(s ...string) *FigureElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *FigureElement) Contenteditable(a FigureContenteditable) *FigureElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *FigureElement) DataUnsafe(name string, s string) *FigureElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *FigureElement) Data(name string, s string) *FigureElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *FigureElement) Dir(a FigureDir) *FigureElement {
	e.attributes["dir"] = a

	return e
}

func (e *FigureElement) Draggable(a FigureDraggable) *FigureElement {
	e.attributes["draggable"] = a

	return e
}

func (e *FigureElement) Enterkeyhint(a FigureEnterkeyhint) *FigureElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *FigureElement) Hidden(a FigureHidden) *FigureElement {
	e.attributes["hidden"] = a

	return e
}

func (e *FigureElement) Id(s string) *FigureElement {
	e.attributes["id"] = s

	return e
}

func (e *FigureElement) Inert(b bool) *FigureElement {
	e.attributes["inert"] = b

	return e
}

func (e *FigureElement) Inputmode(a FigureInputmode) *FigureElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *FigureElement) Itemid(s string) *FigureElement {
	e.attributes["itemid"] = s

	return e
}

func (e *FigureElement) Itemprop(s ...string) *FigureElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *FigureElement) Itemref(s ...string) *FigureElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *FigureElement) Itemscope(b bool) *FigureElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *FigureElement) Itemtype(s ...string) *FigureElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *FigureElement) Lang(s string) *FigureElement {
	e.attributes["lang"] = s

	return e
}

func (e *FigureElement) Nonce(s string) *FigureElement {
	e.attributes["nonce"] = s

	return e
}

func (e *FigureElement) Popover(s string) *FigureElement {
	e.attributes["popover"] = s

	return e
}

func (e *FigureElement) Role(s string) *FigureElement {
	e.attributes["role"] = s

	return e
}

func (e *FigureElement) Slot(s string) *FigureElement {
	e.attributes["slot"] = s

	return e
}

func (e *FigureElement) Spellcheck(a FigureSpellcheck) *FigureElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *FigureElement) Style(s string) *FigureElement {
	e.attributes["style"] = s

	return e
}

func (e *FigureElement) Tabindex(i int) *FigureElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *FigureElement) Title(s string) *FigureElement {
	e.attributes["title"] = s

	return e
}

func (e *FigureElement) Translate(a FigureTranslate) *FigureElement {
	e.attributes["translate"] = a

	return e
}

func (e *FigureElement) Writingsuggestions(a FigureWritingsuggestions) *FigureElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *FigureElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<figure")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</figure>")); err != nil {
		return err
	}

	return nil
}
