// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type HeadElement struct {
	attributes headAttrs
	children   []htemel.Node
	skipRender bool
}

// Head creates a tag <head> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The head element represents a collection of metadata for the Document.
func Head(children ...htemel.Node) *HeadElement {
	node := &HeadElement{
		children:   children,
		attributes: make(headAttrs),
	}

	return node
}

func HeadIf(condition bool, children ...htemel.Node) *HeadElement {
	if condition {
		return Head(children...)
	}

	return &HeadElement{
		children:   children,
		attributes: make(headAttrs),
		skipRender: true,
	}
}

func HeadTernary(condition bool, true htemel.Node, false htemel.Node) *HeadElement {
	if condition {
		return Head(true)
	}
	return Head(false)
}

// Children appends children to this element.
func (e *HeadElement) Children(children ...htemel.Node) *HeadElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *HeadElement) With(fn func(*HeadElement)) *HeadElement {
	fn(e)
	return e
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *HeadElement) Textf(format string, args ...any) *HeadElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *HeadElement) AddClass(classes ...string) *HeadElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *HeadElement) ToggleClass(class string, enable bool) *HeadElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type HeadAutocapitalize string

const (
	HeadAutocapitalizeNone       HeadAutocapitalize = "none"
	HeadAutocapitalizeOff        HeadAutocapitalize = "off"
	HeadAutocapitalizeOn         HeadAutocapitalize = "on"
	HeadAutocapitalizeSentences  HeadAutocapitalize = "sentences"
	HeadAutocapitalizeWords      HeadAutocapitalize = "words"
	HeadAutocapitalizeCharacters HeadAutocapitalize = "characters"
)

type HeadAutocorrect string

const (
	HeadAutocorrectOff   HeadAutocorrect = "off"
	HeadAutocorrectOn    HeadAutocorrect = "on"
	HeadAutocorrectEmpty HeadAutocorrect = ""
)

type HeadContenteditable string

const (
	HeadContenteditableFalse         HeadContenteditable = "false"
	HeadContenteditablePlaintextOnly HeadContenteditable = "plaintext-only"
	HeadContenteditableTrue          HeadContenteditable = "true"
	HeadContenteditableEmpty         HeadContenteditable = ""
)

type HeadDir string

const (
	HeadDirAuto HeadDir = "auto"
	HeadDirLtr  HeadDir = "ltr"
	HeadDirRtl  HeadDir = "rtl"
)

type HeadDraggable string

const (
	HeadDraggableFalse HeadDraggable = "false"
	HeadDraggableTrue  HeadDraggable = "true"
)

type HeadEnterkeyhint string

const (
	HeadEnterkeyhintGo       HeadEnterkeyhint = "go"
	HeadEnterkeyhintNext     HeadEnterkeyhint = "next"
	HeadEnterkeyhintPrevious HeadEnterkeyhint = "previous"
	HeadEnterkeyhintSearch   HeadEnterkeyhint = "search"
	HeadEnterkeyhintSend     HeadEnterkeyhint = "send"
	HeadEnterkeyhintDone     HeadEnterkeyhint = "done"
	HeadEnterkeyhintEnter    HeadEnterkeyhint = "enter"
)

type HeadHidden string

const (
	HeadHiddenHidden     HeadHidden = "hidden"
	HeadHiddenUntilFound HeadHidden = "until-found"
	HeadHiddenEmpty      HeadHidden = ""
)

type HeadInputmode string

const (
	HeadInputmodeText    HeadInputmode = "text"
	HeadInputmodeUrl     HeadInputmode = "url"
	HeadInputmodeDecimal HeadInputmode = "decimal"
	HeadInputmodeEmail   HeadInputmode = "email"
	HeadInputmodeNone    HeadInputmode = "none"
	HeadInputmodeNumeric HeadInputmode = "numeric"
	HeadInputmodeSearch  HeadInputmode = "search"
	HeadInputmodeTel     HeadInputmode = "tel"
)

type HeadSpellcheck string

const (
	HeadSpellcheckFalse HeadSpellcheck = "false"
	HeadSpellcheckTrue  HeadSpellcheck = "true"
	HeadSpellcheckEmpty HeadSpellcheck = ""
)

type HeadTranslate string

const (
	HeadTranslateNo    HeadTranslate = "no"
	HeadTranslateYes   HeadTranslate = "yes"
	HeadTranslateEmpty HeadTranslate = ""
)

type HeadWritingsuggestions string

const (
	HeadWritingsuggestionsTrue  HeadWritingsuggestions = "true"
	HeadWritingsuggestionsFalse HeadWritingsuggestions = "false"
	HeadWritingsuggestionsEmpty HeadWritingsuggestions = ""
)

type headAttrs map[string]any

func (e *HeadElement) AriaUnsafe(name string, s string) *HeadElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *HeadElement) Aria(name string, s string) *HeadElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *HeadElement) Autocapitalize(a HeadAutocapitalize) *HeadElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *HeadElement) Autocorrect(a HeadAutocorrect) *HeadElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *HeadElement) Autofocus(b bool) *HeadElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *HeadElement) Class(s ...string) *HeadElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *HeadElement) Contenteditable(a HeadContenteditable) *HeadElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *HeadElement) DataUnsafe(name string, s string) *HeadElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *HeadElement) Data(name string, s string) *HeadElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *HeadElement) Dir(a HeadDir) *HeadElement {
	e.attributes["dir"] = a

	return e
}

func (e *HeadElement) Draggable(a HeadDraggable) *HeadElement {
	e.attributes["draggable"] = a

	return e
}

func (e *HeadElement) Enterkeyhint(a HeadEnterkeyhint) *HeadElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *HeadElement) Hidden(a HeadHidden) *HeadElement {
	e.attributes["hidden"] = a

	return e
}

func (e *HeadElement) Id(s string) *HeadElement {
	e.attributes["id"] = s

	return e
}

func (e *HeadElement) Inert(b bool) *HeadElement {
	e.attributes["inert"] = b

	return e
}

func (e *HeadElement) Inputmode(a HeadInputmode) *HeadElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *HeadElement) Itemid(s string) *HeadElement {
	e.attributes["itemid"] = s

	return e
}

func (e *HeadElement) Itemprop(s ...string) *HeadElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *HeadElement) Itemref(s ...string) *HeadElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *HeadElement) Itemscope(b bool) *HeadElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *HeadElement) Itemtype(s ...string) *HeadElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *HeadElement) Lang(s string) *HeadElement {
	e.attributes["lang"] = s

	return e
}

func (e *HeadElement) Nonce(s string) *HeadElement {
	e.attributes["nonce"] = s

	return e
}

func (e *HeadElement) Popover(s string) *HeadElement {
	e.attributes["popover"] = s

	return e
}

func (e *HeadElement) Role(s string) *HeadElement {
	e.attributes["role"] = s

	return e
}

func (e *HeadElement) Slot(s string) *HeadElement {
	e.attributes["slot"] = s

	return e
}

func (e *HeadElement) Spellcheck(a HeadSpellcheck) *HeadElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *HeadElement) Style(s string) *HeadElement {
	e.attributes["style"] = s

	return e
}

func (e *HeadElement) Tabindex(i int) *HeadElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *HeadElement) Title(s string) *HeadElement {
	e.attributes["title"] = s

	return e
}

func (e *HeadElement) Translate(a HeadTranslate) *HeadElement {
	e.attributes["translate"] = a

	return e
}

func (e *HeadElement) Writingsuggestions(a HeadWritingsuggestions) *HeadElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *HeadElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<head")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</head>")); err != nil {
		return err
	}

	return nil
}
