// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"golang.org/x/net/html"
)

type HrElement struct {
	attributes hrAttrs

	skipRender bool
}

// Hr creates a tag <hr> instance and returns it for further modification.
//
// Spec Description: The hr element represents a paragraph-level thematic break, e.g., a scene change in a story, or a transition to another topic within a section of a reference book; alternatively, it represents a separator between a set of options of a select element.
func Hr() *HrElement {
	node := &HrElement{

		attributes: make(hrAttrs),
	}

	return node
}

func HrIf(condition bool) *HrElement {
	if condition {
		return Hr()
	}

	return &HrElement{

		attributes: make(hrAttrs),
		skipRender: true,
	}
}

// With allows passing a function to modify the element via a closure.
func (e *HrElement) With(fn func(*HrElement)) *HrElement {
	fn(e)
	return e
}

// AddClass appends a class to the element.
func (e *HrElement) AddClass(classes ...string) *HrElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *HrElement) ToggleClass(class string, enable bool) *HrElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type HrAutocapitalize string

const (
	HrAutocapitalizeNone       HrAutocapitalize = "none"
	HrAutocapitalizeOff        HrAutocapitalize = "off"
	HrAutocapitalizeOn         HrAutocapitalize = "on"
	HrAutocapitalizeSentences  HrAutocapitalize = "sentences"
	HrAutocapitalizeWords      HrAutocapitalize = "words"
	HrAutocapitalizeCharacters HrAutocapitalize = "characters"
)

type HrAutocorrect string

const (
	HrAutocorrectOff   HrAutocorrect = "off"
	HrAutocorrectOn    HrAutocorrect = "on"
	HrAutocorrectEmpty HrAutocorrect = ""
)

type HrContenteditable string

const (
	HrContenteditableTrue          HrContenteditable = "true"
	HrContenteditableFalse         HrContenteditable = "false"
	HrContenteditablePlaintextOnly HrContenteditable = "plaintext-only"
	HrContenteditableEmpty         HrContenteditable = ""
)

type HrDir string

const (
	HrDirAuto HrDir = "auto"
	HrDirLtr  HrDir = "ltr"
	HrDirRtl  HrDir = "rtl"
)

type HrDraggable string

const (
	HrDraggableFalse HrDraggable = "false"
	HrDraggableTrue  HrDraggable = "true"
)

type HrEnterkeyhint string

const (
	HrEnterkeyhintSend     HrEnterkeyhint = "send"
	HrEnterkeyhintDone     HrEnterkeyhint = "done"
	HrEnterkeyhintEnter    HrEnterkeyhint = "enter"
	HrEnterkeyhintGo       HrEnterkeyhint = "go"
	HrEnterkeyhintNext     HrEnterkeyhint = "next"
	HrEnterkeyhintPrevious HrEnterkeyhint = "previous"
	HrEnterkeyhintSearch   HrEnterkeyhint = "search"
)

type HrHidden string

const (
	HrHiddenHidden     HrHidden = "hidden"
	HrHiddenUntilFound HrHidden = "until-found"
	HrHiddenEmpty      HrHidden = ""
)

type HrInputmode string

const (
	HrInputmodeNumeric HrInputmode = "numeric"
	HrInputmodeSearch  HrInputmode = "search"
	HrInputmodeTel     HrInputmode = "tel"
	HrInputmodeText    HrInputmode = "text"
	HrInputmodeUrl     HrInputmode = "url"
	HrInputmodeDecimal HrInputmode = "decimal"
	HrInputmodeEmail   HrInputmode = "email"
	HrInputmodeNone    HrInputmode = "none"
)

type HrSpellcheck string

const (
	HrSpellcheckFalse HrSpellcheck = "false"
	HrSpellcheckTrue  HrSpellcheck = "true"
	HrSpellcheckEmpty HrSpellcheck = ""
)

type HrTranslate string

const (
	HrTranslateNo    HrTranslate = "no"
	HrTranslateYes   HrTranslate = "yes"
	HrTranslateEmpty HrTranslate = ""
)

type HrWritingsuggestions string

const (
	HrWritingsuggestionsFalse HrWritingsuggestions = "false"
	HrWritingsuggestionsTrue  HrWritingsuggestions = "true"
	HrWritingsuggestionsEmpty HrWritingsuggestions = ""
)

type hrAttrs map[string]any

func (e *HrElement) AriaUnsafe(name string, s string) *HrElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *HrElement) Aria(name string, s string) *HrElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *HrElement) Autocapitalize(a HrAutocapitalize) *HrElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *HrElement) Autocorrect(a HrAutocorrect) *HrElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *HrElement) Autofocus(b bool) *HrElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *HrElement) Class(s ...string) *HrElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *HrElement) Contenteditable(a HrContenteditable) *HrElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *HrElement) DataUnsafe(name string, s string) *HrElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *HrElement) Data(name string, s string) *HrElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *HrElement) Dir(a HrDir) *HrElement {
	e.attributes["dir"] = a

	return e
}

func (e *HrElement) Draggable(a HrDraggable) *HrElement {
	e.attributes["draggable"] = a

	return e
}

func (e *HrElement) Enterkeyhint(a HrEnterkeyhint) *HrElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *HrElement) Hidden(a HrHidden) *HrElement {
	e.attributes["hidden"] = a

	return e
}

func (e *HrElement) Id(s string) *HrElement {
	e.attributes["id"] = s

	return e
}

func (e *HrElement) Inert(b bool) *HrElement {
	e.attributes["inert"] = b

	return e
}

func (e *HrElement) Inputmode(a HrInputmode) *HrElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *HrElement) Itemid(s string) *HrElement {
	e.attributes["itemid"] = s

	return e
}

func (e *HrElement) Itemprop(s ...string) *HrElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *HrElement) Itemref(s ...string) *HrElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *HrElement) Itemscope(b bool) *HrElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *HrElement) Itemtype(s ...string) *HrElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *HrElement) Lang(s string) *HrElement {
	e.attributes["lang"] = s

	return e
}

func (e *HrElement) Nonce(s string) *HrElement {
	e.attributes["nonce"] = s

	return e
}

func (e *HrElement) Popover(s string) *HrElement {
	e.attributes["popover"] = s

	return e
}

func (e *HrElement) Role(s string) *HrElement {
	e.attributes["role"] = s

	return e
}

func (e *HrElement) Slot(s string) *HrElement {
	e.attributes["slot"] = s

	return e
}

func (e *HrElement) Spellcheck(a HrSpellcheck) *HrElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *HrElement) Style(s string) *HrElement {
	e.attributes["style"] = s

	return e
}

func (e *HrElement) Tabindex(i int) *HrElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *HrElement) Title(s string) *HrElement {
	e.attributes["title"] = s

	return e
}

func (e *HrElement) Translate(a HrTranslate) *HrElement {
	e.attributes["translate"] = a

	return e
}

func (e *HrElement) Writingsuggestions(a HrWritingsuggestions) *HrElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *HrElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<hr")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	return nil
}
