// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"golang.org/x/net/html"
)

type ImgElement struct {
	attributes imgAttrs

	skipRender bool
}

// Img creates a tag <img> instance and returns it for further modification.
//
// Spec Description: An img element represents an image.
func Img() *ImgElement {
	node := &ImgElement{

		attributes: make(imgAttrs),
	}

	return node
}

func ImgIf(condition bool) *ImgElement {
	if condition {
		return Img()
	}

	return &ImgElement{

		attributes: make(imgAttrs),
		skipRender: true,
	}
}

type ImgCrossorigin string

const (
	ImgCrossoriginAnonymous      ImgCrossorigin = "anonymous"
	ImgCrossoriginUseCredentials ImgCrossorigin = "use-credentials"
	ImgCrossoriginEmpty          ImgCrossorigin = ""
)

type ImgDecoding string

const (
	ImgDecodingAsync ImgDecoding = "async"
	ImgDecodingAuto  ImgDecoding = "auto"
	ImgDecodingSync  ImgDecoding = "sync"
)

type ImgLoading string

const (
	ImgLoadingEager ImgLoading = "eager"
	ImgLoadingLazy  ImgLoading = "lazy"
)

type ImgFetchpriority string

const (
	ImgFetchpriorityAuto ImgFetchpriority = "auto"
	ImgFetchpriorityHigh ImgFetchpriority = "high"
	ImgFetchpriorityLow  ImgFetchpriority = "low"
)

type ImgAutocapitalize string

const (
	ImgAutocapitalizeSentences  ImgAutocapitalize = "sentences"
	ImgAutocapitalizeWords      ImgAutocapitalize = "words"
	ImgAutocapitalizeCharacters ImgAutocapitalize = "characters"
	ImgAutocapitalizeNone       ImgAutocapitalize = "none"
	ImgAutocapitalizeOff        ImgAutocapitalize = "off"
	ImgAutocapitalizeOn         ImgAutocapitalize = "on"
)

type ImgAutocorrect string

const (
	ImgAutocorrectOn    ImgAutocorrect = "on"
	ImgAutocorrectOff   ImgAutocorrect = "off"
	ImgAutocorrectEmpty ImgAutocorrect = ""
)

type ImgContenteditable string

const (
	ImgContenteditablePlaintextOnly ImgContenteditable = "plaintext-only"
	ImgContenteditableTrue          ImgContenteditable = "true"
	ImgContenteditableFalse         ImgContenteditable = "false"
	ImgContenteditableEmpty         ImgContenteditable = ""
)

type ImgDir string

const (
	ImgDirAuto ImgDir = "auto"
	ImgDirLtr  ImgDir = "ltr"
	ImgDirRtl  ImgDir = "rtl"
)

type ImgDraggable string

const (
	ImgDraggableFalse ImgDraggable = "false"
	ImgDraggableTrue  ImgDraggable = "true"
)

type ImgEnterkeyhint string

const (
	ImgEnterkeyhintSend     ImgEnterkeyhint = "send"
	ImgEnterkeyhintDone     ImgEnterkeyhint = "done"
	ImgEnterkeyhintEnter    ImgEnterkeyhint = "enter"
	ImgEnterkeyhintGo       ImgEnterkeyhint = "go"
	ImgEnterkeyhintNext     ImgEnterkeyhint = "next"
	ImgEnterkeyhintPrevious ImgEnterkeyhint = "previous"
	ImgEnterkeyhintSearch   ImgEnterkeyhint = "search"
)

type ImgHidden string

const (
	ImgHiddenHidden     ImgHidden = "hidden"
	ImgHiddenUntilFound ImgHidden = "until-found"
	ImgHiddenEmpty      ImgHidden = ""
)

type ImgInputmode string

const (
	ImgInputmodeNone    ImgInputmode = "none"
	ImgInputmodeNumeric ImgInputmode = "numeric"
	ImgInputmodeSearch  ImgInputmode = "search"
	ImgInputmodeTel     ImgInputmode = "tel"
	ImgInputmodeText    ImgInputmode = "text"
	ImgInputmodeUrl     ImgInputmode = "url"
	ImgInputmodeDecimal ImgInputmode = "decimal"
	ImgInputmodeEmail   ImgInputmode = "email"
)

type ImgSpellcheck string

const (
	ImgSpellcheckFalse ImgSpellcheck = "false"
	ImgSpellcheckTrue  ImgSpellcheck = "true"
	ImgSpellcheckEmpty ImgSpellcheck = ""
)

type ImgTranslate string

const (
	ImgTranslateNo    ImgTranslate = "no"
	ImgTranslateYes   ImgTranslate = "yes"
	ImgTranslateEmpty ImgTranslate = ""
)

type ImgWritingsuggestions string

const (
	ImgWritingsuggestionsFalse ImgWritingsuggestions = "false"
	ImgWritingsuggestionsTrue  ImgWritingsuggestions = "true"
	ImgWritingsuggestionsEmpty ImgWritingsuggestions = ""
)

type imgAttrs map[string]any

func (e *ImgElement) Alt(s string) *ImgElement {
	e.attributes["alt"] = s

	return e
}

func (e *ImgElement) Src(s string) *ImgElement {
	e.attributes["src"] = s

	return e
}

func (e *ImgElement) Srcset(s string) *ImgElement {
	e.attributes["srcset"] = s

	return e
}

func (e *ImgElement) Sizes(s string) *ImgElement {
	e.attributes["sizes"] = s

	return e
}

func (e *ImgElement) Crossorigin(a ImgCrossorigin) *ImgElement {
	e.attributes["crossorigin"] = a

	return e
}

func (e *ImgElement) Usemap(s string) *ImgElement {
	e.attributes["usemap"] = s

	return e
}

func (e *ImgElement) Ismap(b bool) *ImgElement {
	e.attributes["ismap"] = b

	return e
}

func (e *ImgElement) Width(i int) *ImgElement {
	e.attributes["width"] = i

	return e
}

func (e *ImgElement) Height(i int) *ImgElement {
	e.attributes["height"] = i

	return e
}

func (e *ImgElement) Referrerpolicy(s string) *ImgElement {
	e.attributes["referrerpolicy"] = s

	return e
}

func (e *ImgElement) Decoding(a ImgDecoding) *ImgElement {
	e.attributes["decoding"] = a

	return e
}

func (e *ImgElement) Loading(a ImgLoading) *ImgElement {
	e.attributes["loading"] = a

	return e
}

func (e *ImgElement) Fetchpriority(a ImgFetchpriority) *ImgElement {
	e.attributes["fetchpriority"] = a

	return e
}

func (e *ImgElement) AriaUnsafe(name string, s string) *ImgElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ImgElement) Aria(name string, s string) *ImgElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *ImgElement) Autocapitalize(a ImgAutocapitalize) *ImgElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *ImgElement) Autocorrect(a ImgAutocorrect) *ImgElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *ImgElement) Autofocus(b bool) *ImgElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *ImgElement) Class(s ...string) *ImgElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *ImgElement) Contenteditable(a ImgContenteditable) *ImgElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *ImgElement) DataUnsafe(name string, s string) *ImgElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *ImgElement) Data(name string, s string) *ImgElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *ImgElement) Dir(a ImgDir) *ImgElement {
	e.attributes["dir"] = a

	return e
}

func (e *ImgElement) Draggable(a ImgDraggable) *ImgElement {
	e.attributes["draggable"] = a

	return e
}

func (e *ImgElement) Enterkeyhint(a ImgEnterkeyhint) *ImgElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *ImgElement) Hidden(a ImgHidden) *ImgElement {
	e.attributes["hidden"] = a

	return e
}

func (e *ImgElement) Id(s string) *ImgElement {
	e.attributes["id"] = s

	return e
}

func (e *ImgElement) Inert(b bool) *ImgElement {
	e.attributes["inert"] = b

	return e
}

func (e *ImgElement) Inputmode(a ImgInputmode) *ImgElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *ImgElement) Itemid(s string) *ImgElement {
	e.attributes["itemid"] = s

	return e
}

func (e *ImgElement) Itemprop(s ...string) *ImgElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *ImgElement) Itemref(s ...string) *ImgElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *ImgElement) Itemscope(b bool) *ImgElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *ImgElement) Itemtype(s ...string) *ImgElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *ImgElement) Lang(s string) *ImgElement {
	e.attributes["lang"] = s

	return e
}

func (e *ImgElement) Nonce(s string) *ImgElement {
	e.attributes["nonce"] = s

	return e
}

func (e *ImgElement) Popover(s string) *ImgElement {
	e.attributes["popover"] = s

	return e
}

func (e *ImgElement) Slot(s string) *ImgElement {
	e.attributes["slot"] = s

	return e
}

func (e *ImgElement) Spellcheck(a ImgSpellcheck) *ImgElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *ImgElement) Style(s string) *ImgElement {
	e.attributes["style"] = s

	return e
}

func (e *ImgElement) Tabindex(i int) *ImgElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *ImgElement) Title(s string) *ImgElement {
	e.attributes["title"] = s

	return e
}

func (e *ImgElement) Translate(a ImgTranslate) *ImgElement {
	e.attributes["translate"] = a

	return e
}

func (e *ImgElement) Writingsuggestions(a ImgWritingsuggestions) *ImgElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *ImgElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<img")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	return nil
}
