// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type LegendElement struct {
	attributes legendAttrs
	children   []htemel.Node
	skipRender bool
}

// Legend creates a tag <legend> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The legend element represents a caption for the rest of the contents of the legend element's parent fieldset element, if any. Otherwise, if the legend has a parent optgroup element, then the legend represents the optgroup's label.
func Legend(children ...htemel.Node) *LegendElement {
	node := &LegendElement{
		children:   children,
		attributes: make(legendAttrs),
	}

	return node
}

func LegendIf(condition bool, children ...htemel.Node) *LegendElement {
	if condition {
		return Legend(children...)
	}

	return &LegendElement{
		children:   children,
		attributes: make(legendAttrs),
		skipRender: true,
	}
}

func LegendTernary(condition bool, true htemel.Node, false htemel.Node) *LegendElement {
	if condition {
		return Legend(true)
	}
	return Legend(false)
}

// Children appends children to this element.
func (e *LegendElement) Children(children ...htemel.Node) *LegendElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *LegendElement) With(fn func(*LegendElement)) *LegendElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *LegendElement) Text(text string) *LegendElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *LegendElement) Textf(format string, args ...any) *LegendElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// If conditionally adds a child node to the element if the condition is true, otherwise it is a no-op.
func (e *LegendElement) If(cond bool, child htemel.Node) *LegendElement {
	if cond {
		return e.Children(child)
	}
	return e
}

func (e *LegendElement) IfElse(cond bool, then, els htemel.Node) *LegendElement {
	if cond {
		e.Children(then)
	} else {
		e.Children(els)
	}
	return e
}

// IfThen conditionally calls the given function with the element if the condition is true, otherwise it is a no-op.
func (e *LegendElement) IfThen(cond bool, fn func(*LegendElement)) *LegendElement {
	if cond {
		fn(e)
	}
	return e
}

// AddClass appends a class to the element.
func (e *LegendElement) AddClass(classes ...string) *LegendElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *LegendElement) ToggleClass(class string, enable bool) *LegendElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type LegendAutocapitalize string

const (
	LegendAutocapitalizeOn         LegendAutocapitalize = "on"
	LegendAutocapitalizeSentences  LegendAutocapitalize = "sentences"
	LegendAutocapitalizeWords      LegendAutocapitalize = "words"
	LegendAutocapitalizeCharacters LegendAutocapitalize = "characters"
	LegendAutocapitalizeNone       LegendAutocapitalize = "none"
	LegendAutocapitalizeOff        LegendAutocapitalize = "off"
)

type LegendAutocorrect string

const (
	LegendAutocorrectOff   LegendAutocorrect = "off"
	LegendAutocorrectOn    LegendAutocorrect = "on"
	LegendAutocorrectEmpty LegendAutocorrect = ""
)

type LegendContenteditable string

const (
	LegendContenteditableFalse         LegendContenteditable = "false"
	LegendContenteditablePlaintextOnly LegendContenteditable = "plaintext-only"
	LegendContenteditableTrue          LegendContenteditable = "true"
	LegendContenteditableEmpty         LegendContenteditable = ""
)

type LegendDir string

const (
	LegendDirAuto LegendDir = "auto"
	LegendDirLtr  LegendDir = "ltr"
	LegendDirRtl  LegendDir = "rtl"
)

type LegendDraggable string

const (
	LegendDraggableFalse LegendDraggable = "false"
	LegendDraggableTrue  LegendDraggable = "true"
)

type LegendEnterkeyhint string

const (
	LegendEnterkeyhintNext     LegendEnterkeyhint = "next"
	LegendEnterkeyhintPrevious LegendEnterkeyhint = "previous"
	LegendEnterkeyhintSearch   LegendEnterkeyhint = "search"
	LegendEnterkeyhintSend     LegendEnterkeyhint = "send"
	LegendEnterkeyhintDone     LegendEnterkeyhint = "done"
	LegendEnterkeyhintEnter    LegendEnterkeyhint = "enter"
	LegendEnterkeyhintGo       LegendEnterkeyhint = "go"
)

type LegendHidden string

const (
	LegendHiddenHidden     LegendHidden = "hidden"
	LegendHiddenUntilFound LegendHidden = "until-found"
	LegendHiddenEmpty      LegendHidden = ""
)

type LegendInputmode string

const (
	LegendInputmodeNumeric LegendInputmode = "numeric"
	LegendInputmodeSearch  LegendInputmode = "search"
	LegendInputmodeTel     LegendInputmode = "tel"
	LegendInputmodeText    LegendInputmode = "text"
	LegendInputmodeUrl     LegendInputmode = "url"
	LegendInputmodeDecimal LegendInputmode = "decimal"
	LegendInputmodeEmail   LegendInputmode = "email"
	LegendInputmodeNone    LegendInputmode = "none"
)

type LegendSpellcheck string

const (
	LegendSpellcheckFalse LegendSpellcheck = "false"
	LegendSpellcheckTrue  LegendSpellcheck = "true"
	LegendSpellcheckEmpty LegendSpellcheck = ""
)

type LegendTranslate string

const (
	LegendTranslateNo    LegendTranslate = "no"
	LegendTranslateYes   LegendTranslate = "yes"
	LegendTranslateEmpty LegendTranslate = ""
)

type LegendWritingsuggestions string

const (
	LegendWritingsuggestionsFalse LegendWritingsuggestions = "false"
	LegendWritingsuggestionsTrue  LegendWritingsuggestions = "true"
	LegendWritingsuggestionsEmpty LegendWritingsuggestions = ""
)

type legendAttrs map[string]any

func (e *LegendElement) AriaUnsafe(name string, s string) *LegendElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *LegendElement) Aria(name string, s string) *LegendElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *LegendElement) Autocapitalize(a LegendAutocapitalize) *LegendElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *LegendElement) Autocorrect(a LegendAutocorrect) *LegendElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *LegendElement) Autofocus(b bool) *LegendElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *LegendElement) Class(s ...string) *LegendElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *LegendElement) Contenteditable(a LegendContenteditable) *LegendElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *LegendElement) DataUnsafe(name string, s string) *LegendElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *LegendElement) Data(name string, s string) *LegendElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *LegendElement) Dir(a LegendDir) *LegendElement {
	e.attributes["dir"] = a

	return e
}

func (e *LegendElement) Draggable(a LegendDraggable) *LegendElement {
	e.attributes["draggable"] = a

	return e
}

func (e *LegendElement) Enterkeyhint(a LegendEnterkeyhint) *LegendElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *LegendElement) Hidden(a LegendHidden) *LegendElement {
	e.attributes["hidden"] = a

	return e
}

func (e *LegendElement) Id(s string) *LegendElement {
	e.attributes["id"] = s

	return e
}

func (e *LegendElement) Inert(b bool) *LegendElement {
	e.attributes["inert"] = b

	return e
}

func (e *LegendElement) Inputmode(a LegendInputmode) *LegendElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *LegendElement) Itemid(s string) *LegendElement {
	e.attributes["itemid"] = s

	return e
}

func (e *LegendElement) Itemprop(s ...string) *LegendElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *LegendElement) Itemref(s ...string) *LegendElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *LegendElement) Itemscope(b bool) *LegendElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *LegendElement) Itemtype(s ...string) *LegendElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *LegendElement) Lang(s string) *LegendElement {
	e.attributes["lang"] = s

	return e
}

func (e *LegendElement) Nonce(s string) *LegendElement {
	e.attributes["nonce"] = s

	return e
}

func (e *LegendElement) Popover(s string) *LegendElement {
	e.attributes["popover"] = s

	return e
}

func (e *LegendElement) Role(s string) *LegendElement {
	e.attributes["role"] = s

	return e
}

func (e *LegendElement) Slot(s string) *LegendElement {
	e.attributes["slot"] = s

	return e
}

func (e *LegendElement) Spellcheck(a LegendSpellcheck) *LegendElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *LegendElement) Style(s string) *LegendElement {
	e.attributes["style"] = s

	return e
}

func (e *LegendElement) Tabindex(i int) *LegendElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *LegendElement) Title(s string) *LegendElement {
	e.attributes["title"] = s

	return e
}

func (e *LegendElement) Translate(a LegendTranslate) *LegendElement {
	e.attributes["translate"] = a

	return e
}

func (e *LegendElement) Writingsuggestions(a LegendWritingsuggestions) *LegendElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *LegendElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<legend")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</legend>")

	_, err := io.WriteString(w, sb.String())
	return err
}
