// Code generated by htemel. DO NOT EDIT.
package html

import (
  "fmt"
  "github.com/derekmwright/htemel"
  "golang.org/x/net/html"
  "io"
  "strings"
)

type MetaElement struct {
	attributes metaAttrs
	children []htemel.Node
	skipRender bool
}

// Meta creates a tag <meta> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The meta element represents various kinds of metadata that cannot be expressed using the title, base, link, style, and script elements.
func Meta(children ...htemel.Node) *MetaElement {
	node := &MetaElement{
		children: children,
		attributes: make(metaAttrs),
	}

	return node
}

func MetaIf(condition bool, children ...htemel.Node) *MetaElement {
	if condition {
		return Meta(children...)
	}

	return &MetaElement{
		skipRender: true,
	}
}

type MetaAutocapitalizeEnum string

const (
	MetaAutocapitalizeEnumOn MetaAutocapitalizeEnum = "on"
	MetaAutocapitalizeEnumSentences MetaAutocapitalizeEnum = "sentences"
	MetaAutocapitalizeEnumWords MetaAutocapitalizeEnum = "words"
	MetaAutocapitalizeEnumCharacters MetaAutocapitalizeEnum = "characters"
	MetaAutocapitalizeEnumNone MetaAutocapitalizeEnum = "none"
	MetaAutocapitalizeEnumOff MetaAutocapitalizeEnum = "off"
)

type MetaAutocorrectEnum string

const (
	MetaAutocorrectEnumOff MetaAutocorrectEnum = "off"
	MetaAutocorrectEnumOn MetaAutocorrectEnum = "on"
)

type MetaContenteditableEnum string

const (
	MetaContenteditableEnumFalse MetaContenteditableEnum = "false"
	MetaContenteditableEnumPlaintextOnly MetaContenteditableEnum = "plaintext-only"
	MetaContenteditableEnumTrue MetaContenteditableEnum = "true"
)

type MetaDirEnum string

const (
	MetaDirEnumAuto MetaDirEnum = "auto"
	MetaDirEnumLtr MetaDirEnum = "ltr"
	MetaDirEnumRtl MetaDirEnum = "rtl"
)

type MetaDraggableEnum string

const (
	MetaDraggableEnumFalse MetaDraggableEnum = "false"
	MetaDraggableEnumTrue MetaDraggableEnum = "true"
)

type MetaEnterkeyhintEnum string

const (
	MetaEnterkeyhintEnumEnter MetaEnterkeyhintEnum = "enter"
	MetaEnterkeyhintEnumGo MetaEnterkeyhintEnum = "go"
	MetaEnterkeyhintEnumNext MetaEnterkeyhintEnum = "next"
	MetaEnterkeyhintEnumPrevious MetaEnterkeyhintEnum = "previous"
	MetaEnterkeyhintEnumSearch MetaEnterkeyhintEnum = "search"
	MetaEnterkeyhintEnumSend MetaEnterkeyhintEnum = "send"
	MetaEnterkeyhintEnumDone MetaEnterkeyhintEnum = "done"
)

type MetaHiddenEnum string

const (
	MetaHiddenEnumHidden MetaHiddenEnum = "hidden"
	MetaHiddenEnumUntilFound MetaHiddenEnum = "until-found"
)

type metaAttrs map[string]any

func (e *MetaElement) Autocapitalize(a MetaAutocapitalizeEnum) *MetaElement {
	e.attributes["autocapitalize"] = a
	
	return e
}

func (e *MetaElement) Autocorrect(a MetaAutocorrectEnum) *MetaElement {
	e.attributes["autocorrect"] = a
	
	return e
}

func (e *MetaElement) Autofocus(b bool) *MetaElement {
	e.attributes["autofocus"] = b
	
	return e
}

func (e *MetaElement) Class(s ...string) *MetaElement {
	e.attributes["class"] = strings.Join(s, " ")
	
	return e
}

func (e *MetaElement) Contenteditable(a MetaContenteditableEnum) *MetaElement {
	e.attributes["contenteditable"] = a
	
	return e
}

func (e *MetaElement) Dir(a MetaDirEnum) *MetaElement {
	e.attributes["dir"] = a
	
	return e
}

func (e *MetaElement) Draggable(a MetaDraggableEnum) *MetaElement {
	e.attributes["draggable"] = a
	
	return e
}

func (e *MetaElement) Enterkeyhint(a MetaEnterkeyhintEnum) *MetaElement {
	e.attributes["enterkeyhint"] = a
	
	return e
}

func (e *MetaElement) Hidden(a MetaHiddenEnum) *MetaElement {
	e.attributes["hidden"] = a
	
	return e
}

func (e *MetaElement) Id(s string) *MetaElement {
	e.attributes["id"] = s
	
	return e
}

func (e *MetaElement) Slot(s string) *MetaElement {
	e.attributes["slot"] = s
	
	return e
}

func (e *MetaElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<meta")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key + "="))
		w.Write([]byte("\"" + html.EscapeString(fmt.Sprintf("%v", v)) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</meta>")); err != nil {
		return err
	}

	return nil
}
