// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type MeterElement struct {
	attributes meterAttrs
	children   []htemel.Node
	skipRender bool
}

// Meter creates a tag <meter> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The meter element represents a scalar measurement within a known range, or a fractional value; for example disk usage, the relevance of a query result, or the fraction of a voting population to have selected a particular candidate.
func Meter(children ...htemel.Node) *MeterElement {
	node := &MeterElement{
		children:   children,
		attributes: make(meterAttrs),
	}

	return node
}

func MeterIf(condition bool, children ...htemel.Node) *MeterElement {
	if condition {
		return Meter(children...)
	}

	return &MeterElement{
		children:   children,
		attributes: make(meterAttrs),
		skipRender: true,
	}
}

func MeterTernary(condition bool, true htemel.Node, false htemel.Node) *MeterElement {
	if condition {
		return Meter(true)
	}
	return Meter(false)
}

// Children appends children to this element.
func (e *MeterElement) Children(children ...htemel.Node) *MeterElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *MeterElement) With(fn func(*MeterElement)) *MeterElement {
	fn(e)
	return e
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *MeterElement) Textf(format string, args ...any) *MeterElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *MeterElement) AddClass(classes ...string) *MeterElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *MeterElement) ToggleClass(class string, enable bool) *MeterElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type MeterAutocapitalize string

const (
	MeterAutocapitalizeSentences  MeterAutocapitalize = "sentences"
	MeterAutocapitalizeWords      MeterAutocapitalize = "words"
	MeterAutocapitalizeCharacters MeterAutocapitalize = "characters"
	MeterAutocapitalizeNone       MeterAutocapitalize = "none"
	MeterAutocapitalizeOff        MeterAutocapitalize = "off"
	MeterAutocapitalizeOn         MeterAutocapitalize = "on"
)

type MeterAutocorrect string

const (
	MeterAutocorrectOff   MeterAutocorrect = "off"
	MeterAutocorrectOn    MeterAutocorrect = "on"
	MeterAutocorrectEmpty MeterAutocorrect = ""
)

type MeterContenteditable string

const (
	MeterContenteditableFalse         MeterContenteditable = "false"
	MeterContenteditablePlaintextOnly MeterContenteditable = "plaintext-only"
	MeterContenteditableTrue          MeterContenteditable = "true"
	MeterContenteditableEmpty         MeterContenteditable = ""
)

type MeterDir string

const (
	MeterDirAuto MeterDir = "auto"
	MeterDirLtr  MeterDir = "ltr"
	MeterDirRtl  MeterDir = "rtl"
)

type MeterDraggable string

const (
	MeterDraggableFalse MeterDraggable = "false"
	MeterDraggableTrue  MeterDraggable = "true"
)

type MeterEnterkeyhint string

const (
	MeterEnterkeyhintGo       MeterEnterkeyhint = "go"
	MeterEnterkeyhintNext     MeterEnterkeyhint = "next"
	MeterEnterkeyhintPrevious MeterEnterkeyhint = "previous"
	MeterEnterkeyhintSearch   MeterEnterkeyhint = "search"
	MeterEnterkeyhintSend     MeterEnterkeyhint = "send"
	MeterEnterkeyhintDone     MeterEnterkeyhint = "done"
	MeterEnterkeyhintEnter    MeterEnterkeyhint = "enter"
)

type MeterHidden string

const (
	MeterHiddenHidden     MeterHidden = "hidden"
	MeterHiddenUntilFound MeterHidden = "until-found"
	MeterHiddenEmpty      MeterHidden = ""
)

type MeterInputmode string

const (
	MeterInputmodeDecimal MeterInputmode = "decimal"
	MeterInputmodeEmail   MeterInputmode = "email"
	MeterInputmodeNone    MeterInputmode = "none"
	MeterInputmodeNumeric MeterInputmode = "numeric"
	MeterInputmodeSearch  MeterInputmode = "search"
	MeterInputmodeTel     MeterInputmode = "tel"
	MeterInputmodeText    MeterInputmode = "text"
	MeterInputmodeUrl     MeterInputmode = "url"
)

type MeterSpellcheck string

const (
	MeterSpellcheckFalse MeterSpellcheck = "false"
	MeterSpellcheckTrue  MeterSpellcheck = "true"
	MeterSpellcheckEmpty MeterSpellcheck = ""
)

type MeterTranslate string

const (
	MeterTranslateNo    MeterTranslate = "no"
	MeterTranslateYes   MeterTranslate = "yes"
	MeterTranslateEmpty MeterTranslate = ""
)

type MeterWritingsuggestions string

const (
	MeterWritingsuggestionsFalse MeterWritingsuggestions = "false"
	MeterWritingsuggestionsTrue  MeterWritingsuggestions = "true"
	MeterWritingsuggestionsEmpty MeterWritingsuggestions = ""
)

type meterAttrs map[string]any

func (e *MeterElement) Value(f float64) *MeterElement {
	e.attributes["value"] = f

	return e
}

func (e *MeterElement) Min(f float64) *MeterElement {
	e.attributes["min"] = f

	return e
}

func (e *MeterElement) Max(f float64) *MeterElement {
	e.attributes["max"] = f

	return e
}

func (e *MeterElement) Low(f float64) *MeterElement {
	e.attributes["low"] = f

	return e
}

func (e *MeterElement) High(f float64) *MeterElement {
	e.attributes["high"] = f

	return e
}

func (e *MeterElement) Optimum(f float64) *MeterElement {
	e.attributes["optimum"] = f

	return e
}

func (e *MeterElement) AriaUnsafe(name string, s string) *MeterElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *MeterElement) Aria(name string, s string) *MeterElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *MeterElement) Autocapitalize(a MeterAutocapitalize) *MeterElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *MeterElement) Autocorrect(a MeterAutocorrect) *MeterElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *MeterElement) Autofocus(b bool) *MeterElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *MeterElement) Class(s ...string) *MeterElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *MeterElement) Contenteditable(a MeterContenteditable) *MeterElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *MeterElement) DataUnsafe(name string, s string) *MeterElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *MeterElement) Data(name string, s string) *MeterElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *MeterElement) Dir(a MeterDir) *MeterElement {
	e.attributes["dir"] = a

	return e
}

func (e *MeterElement) Draggable(a MeterDraggable) *MeterElement {
	e.attributes["draggable"] = a

	return e
}

func (e *MeterElement) Enterkeyhint(a MeterEnterkeyhint) *MeterElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *MeterElement) Hidden(a MeterHidden) *MeterElement {
	e.attributes["hidden"] = a

	return e
}

func (e *MeterElement) Id(s string) *MeterElement {
	e.attributes["id"] = s

	return e
}

func (e *MeterElement) Inert(b bool) *MeterElement {
	e.attributes["inert"] = b

	return e
}

func (e *MeterElement) Inputmode(a MeterInputmode) *MeterElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *MeterElement) Itemid(s string) *MeterElement {
	e.attributes["itemid"] = s

	return e
}

func (e *MeterElement) Itemprop(s ...string) *MeterElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *MeterElement) Itemref(s ...string) *MeterElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *MeterElement) Itemscope(b bool) *MeterElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *MeterElement) Itemtype(s ...string) *MeterElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *MeterElement) Lang(s string) *MeterElement {
	e.attributes["lang"] = s

	return e
}

func (e *MeterElement) Nonce(s string) *MeterElement {
	e.attributes["nonce"] = s

	return e
}

func (e *MeterElement) Popover(s string) *MeterElement {
	e.attributes["popover"] = s

	return e
}

func (e *MeterElement) Role(s string) *MeterElement {
	e.attributes["role"] = s

	return e
}

func (e *MeterElement) Slot(s string) *MeterElement {
	e.attributes["slot"] = s

	return e
}

func (e *MeterElement) Spellcheck(a MeterSpellcheck) *MeterElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *MeterElement) Style(s string) *MeterElement {
	e.attributes["style"] = s

	return e
}

func (e *MeterElement) Tabindex(i int) *MeterElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *MeterElement) Title(s string) *MeterElement {
	e.attributes["title"] = s

	return e
}

func (e *MeterElement) Translate(a MeterTranslate) *MeterElement {
	e.attributes["translate"] = a

	return e
}

func (e *MeterElement) Writingsuggestions(a MeterWritingsuggestions) *MeterElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *MeterElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<meter")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</meter>")); err != nil {
		return err
	}

	return nil
}
