// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type OptgroupElement struct {
	attributes optgroupAttrs
	children   []htemel.Node
	skipRender bool
}

// Optgroup creates a tag <optgroup> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The optgroup element represents a group of option elements with a common label.
func Optgroup(children ...htemel.Node) *OptgroupElement {
	node := &OptgroupElement{
		children:   children,
		attributes: make(optgroupAttrs),
	}

	return node
}

func OptgroupIf(condition bool, children ...htemel.Node) *OptgroupElement {
	if condition {
		return Optgroup(children...)
	}

	return &OptgroupElement{
		children:   children,
		attributes: make(optgroupAttrs),
		skipRender: true,
	}
}

func OptgroupTernary(condition bool, true htemel.Node, false htemel.Node) *OptgroupElement {
	if condition {
		return Optgroup(true)
	}

	return Optgroup(false)
}

type OptgroupAutocapitalize string

const (
	OptgroupAutocapitalizeSentences  OptgroupAutocapitalize = "sentences"
	OptgroupAutocapitalizeWords      OptgroupAutocapitalize = "words"
	OptgroupAutocapitalizeCharacters OptgroupAutocapitalize = "characters"
	OptgroupAutocapitalizeNone       OptgroupAutocapitalize = "none"
	OptgroupAutocapitalizeOff        OptgroupAutocapitalize = "off"
	OptgroupAutocapitalizeOn         OptgroupAutocapitalize = "on"
)

type OptgroupAutocorrect string

const (
	OptgroupAutocorrectOn    OptgroupAutocorrect = "on"
	OptgroupAutocorrectOff   OptgroupAutocorrect = "off"
	OptgroupAutocorrectEmpty OptgroupAutocorrect = ""
)

type OptgroupContenteditable string

const (
	OptgroupContenteditablePlaintextOnly OptgroupContenteditable = "plaintext-only"
	OptgroupContenteditableTrue          OptgroupContenteditable = "true"
	OptgroupContenteditableFalse         OptgroupContenteditable = "false"
	OptgroupContenteditableEmpty         OptgroupContenteditable = ""
)

type OptgroupDir string

const (
	OptgroupDirAuto OptgroupDir = "auto"
	OptgroupDirLtr  OptgroupDir = "ltr"
	OptgroupDirRtl  OptgroupDir = "rtl"
)

type OptgroupDraggable string

const (
	OptgroupDraggableFalse OptgroupDraggable = "false"
	OptgroupDraggableTrue  OptgroupDraggable = "true"
)

type OptgroupEnterkeyhint string

const (
	OptgroupEnterkeyhintDone     OptgroupEnterkeyhint = "done"
	OptgroupEnterkeyhintEnter    OptgroupEnterkeyhint = "enter"
	OptgroupEnterkeyhintGo       OptgroupEnterkeyhint = "go"
	OptgroupEnterkeyhintNext     OptgroupEnterkeyhint = "next"
	OptgroupEnterkeyhintPrevious OptgroupEnterkeyhint = "previous"
	OptgroupEnterkeyhintSearch   OptgroupEnterkeyhint = "search"
	OptgroupEnterkeyhintSend     OptgroupEnterkeyhint = "send"
)

type OptgroupHidden string

const (
	OptgroupHiddenHidden     OptgroupHidden = "hidden"
	OptgroupHiddenUntilFound OptgroupHidden = "until-found"
	OptgroupHiddenEmpty      OptgroupHidden = ""
)

type OptgroupInputmode string

const (
	OptgroupInputmodeTel     OptgroupInputmode = "tel"
	OptgroupInputmodeText    OptgroupInputmode = "text"
	OptgroupInputmodeUrl     OptgroupInputmode = "url"
	OptgroupInputmodeDecimal OptgroupInputmode = "decimal"
	OptgroupInputmodeEmail   OptgroupInputmode = "email"
	OptgroupInputmodeNone    OptgroupInputmode = "none"
	OptgroupInputmodeNumeric OptgroupInputmode = "numeric"
	OptgroupInputmodeSearch  OptgroupInputmode = "search"
)

type OptgroupSpellcheck string

const (
	OptgroupSpellcheckFalse OptgroupSpellcheck = "false"
	OptgroupSpellcheckTrue  OptgroupSpellcheck = "true"
	OptgroupSpellcheckEmpty OptgroupSpellcheck = ""
)

type OptgroupTranslate string

const (
	OptgroupTranslateYes   OptgroupTranslate = "yes"
	OptgroupTranslateNo    OptgroupTranslate = "no"
	OptgroupTranslateEmpty OptgroupTranslate = ""
)

type OptgroupWritingsuggestions string

const (
	OptgroupWritingsuggestionsFalse OptgroupWritingsuggestions = "false"
	OptgroupWritingsuggestionsTrue  OptgroupWritingsuggestions = "true"
	OptgroupWritingsuggestionsEmpty OptgroupWritingsuggestions = ""
)

type optgroupAttrs map[string]any

func (e *OptgroupElement) Disabled(b bool) *OptgroupElement {
	e.attributes["disabled"] = b

	return e
}

func (e *OptgroupElement) Label(s string) *OptgroupElement {
	e.attributes["label"] = s

	return e
}

func (e *OptgroupElement) AriaUnsafe(name string, s string) *OptgroupElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *OptgroupElement) Aria(name string, s string) *OptgroupElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *OptgroupElement) Autocapitalize(a OptgroupAutocapitalize) *OptgroupElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *OptgroupElement) Autocorrect(a OptgroupAutocorrect) *OptgroupElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *OptgroupElement) Autofocus(b bool) *OptgroupElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *OptgroupElement) Class(s ...string) *OptgroupElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *OptgroupElement) Contenteditable(a OptgroupContenteditable) *OptgroupElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *OptgroupElement) DataUnsafe(name string, s string) *OptgroupElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *OptgroupElement) Data(name string, s string) *OptgroupElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *OptgroupElement) Dir(a OptgroupDir) *OptgroupElement {
	e.attributes["dir"] = a

	return e
}

func (e *OptgroupElement) Draggable(a OptgroupDraggable) *OptgroupElement {
	e.attributes["draggable"] = a

	return e
}

func (e *OptgroupElement) Enterkeyhint(a OptgroupEnterkeyhint) *OptgroupElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *OptgroupElement) Hidden(a OptgroupHidden) *OptgroupElement {
	e.attributes["hidden"] = a

	return e
}

func (e *OptgroupElement) Id(s string) *OptgroupElement {
	e.attributes["id"] = s

	return e
}

func (e *OptgroupElement) Inert(b bool) *OptgroupElement {
	e.attributes["inert"] = b

	return e
}

func (e *OptgroupElement) Inputmode(a OptgroupInputmode) *OptgroupElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *OptgroupElement) Itemid(s string) *OptgroupElement {
	e.attributes["itemid"] = s

	return e
}

func (e *OptgroupElement) Itemprop(s ...string) *OptgroupElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *OptgroupElement) Itemref(s ...string) *OptgroupElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *OptgroupElement) Itemscope(b bool) *OptgroupElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *OptgroupElement) Itemtype(s ...string) *OptgroupElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *OptgroupElement) Lang(s string) *OptgroupElement {
	e.attributes["lang"] = s

	return e
}

func (e *OptgroupElement) Nonce(s string) *OptgroupElement {
	e.attributes["nonce"] = s

	return e
}

func (e *OptgroupElement) Popover(s string) *OptgroupElement {
	e.attributes["popover"] = s

	return e
}

func (e *OptgroupElement) Slot(s string) *OptgroupElement {
	e.attributes["slot"] = s

	return e
}

func (e *OptgroupElement) Spellcheck(a OptgroupSpellcheck) *OptgroupElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *OptgroupElement) Style(s string) *OptgroupElement {
	e.attributes["style"] = s

	return e
}

func (e *OptgroupElement) Tabindex(i int) *OptgroupElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *OptgroupElement) Title(s string) *OptgroupElement {
	e.attributes["title"] = s

	return e
}

func (e *OptgroupElement) Translate(a OptgroupTranslate) *OptgroupElement {
	e.attributes["translate"] = a

	return e
}

func (e *OptgroupElement) Writingsuggestions(a OptgroupWritingsuggestions) *OptgroupElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *OptgroupElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<optgroup")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</optgroup>")); err != nil {
		return err
	}

	return nil
}
