// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type OptionElement struct {
	children []htemel.Node
	skipRender bool
}

// Option creates a tag <option> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The option element represents an option in a select element or as part of a list of suggestions in a datalist element.
func Option(children ...htemel.Node) *OptionElement {
	node := &OptionElement{
		children: children,
	}

	return node
}

func OptionIf(condition bool, children ...htemel.Node) *OptionElement {
	if condition {
		return Option(children...)
	}

	return &OptionElement{
		skipRender: true,
	}
}

func (e *OptionElement) Autocapitalize() *OptionElement {
	return e
}

func (e *OptionElement) Autocorrect() *OptionElement {
	return e
}

func (e *OptionElement) Autofocus() *OptionElement {
	return e
}

func (e *OptionElement) Class() *OptionElement {
	return e
}

func (e *OptionElement) Contenteditable() *OptionElement {
	return e
}

func (e *OptionElement) Id() *OptionElement {
	return e
}

func (e *OptionElement) Slot() *OptionElement {
	return e
}

func (e *OptionElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<option")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</option>")); err != nil {
		return err
	}

	return nil
}
