// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type OutputElement struct {
	attributes outputAttrs
	children   []htemel.Node
	skipRender bool
}

// Output creates a tag <output> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The output element represents the result of a calculation performed by the application, or the result of a user action.
func Output(children ...htemel.Node) *OutputElement {
	node := &OutputElement{
		children:   children,
		attributes: make(outputAttrs),
	}

	return node
}

func OutputIf(condition bool, children ...htemel.Node) *OutputElement {
	if condition {
		return Output(children...)
	}

	return &OutputElement{
		children:   children,
		attributes: make(outputAttrs),
		skipRender: true,
	}
}

func OutputTernary(condition bool, true htemel.Node, false htemel.Node) *OutputElement {
	if condition {
		return Output(true)
	}
	return Output(false)
}

// Children appends children to this element.
func (e *OutputElement) Children(children ...htemel.Node) *OutputElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *OutputElement) With(fn func(*OutputElement)) *OutputElement {
	fn(e)
	return e
}

// Text adds a text node to the element.
func (e *OutputElement) Text(text string) *OutputElement {
	return e.Children(htemel.Text(text))
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *OutputElement) Textf(format string, args ...any) *OutputElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *OutputElement) AddClass(classes ...string) *OutputElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *OutputElement) ToggleClass(class string, enable bool) *OutputElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type OutputAutocapitalize string

const (
	OutputAutocapitalizeCharacters OutputAutocapitalize = "characters"
	OutputAutocapitalizeNone       OutputAutocapitalize = "none"
	OutputAutocapitalizeOff        OutputAutocapitalize = "off"
	OutputAutocapitalizeOn         OutputAutocapitalize = "on"
	OutputAutocapitalizeSentences  OutputAutocapitalize = "sentences"
	OutputAutocapitalizeWords      OutputAutocapitalize = "words"
)

type OutputAutocorrect string

const (
	OutputAutocorrectOff   OutputAutocorrect = "off"
	OutputAutocorrectOn    OutputAutocorrect = "on"
	OutputAutocorrectEmpty OutputAutocorrect = ""
)

type OutputContenteditable string

const (
	OutputContenteditableFalse         OutputContenteditable = "false"
	OutputContenteditablePlaintextOnly OutputContenteditable = "plaintext-only"
	OutputContenteditableTrue          OutputContenteditable = "true"
	OutputContenteditableEmpty         OutputContenteditable = ""
)

type OutputDir string

const (
	OutputDirRtl  OutputDir = "rtl"
	OutputDirAuto OutputDir = "auto"
	OutputDirLtr  OutputDir = "ltr"
)

type OutputDraggable string

const (
	OutputDraggableFalse OutputDraggable = "false"
	OutputDraggableTrue  OutputDraggable = "true"
)

type OutputEnterkeyhint string

const (
	OutputEnterkeyhintGo       OutputEnterkeyhint = "go"
	OutputEnterkeyhintNext     OutputEnterkeyhint = "next"
	OutputEnterkeyhintPrevious OutputEnterkeyhint = "previous"
	OutputEnterkeyhintSearch   OutputEnterkeyhint = "search"
	OutputEnterkeyhintSend     OutputEnterkeyhint = "send"
	OutputEnterkeyhintDone     OutputEnterkeyhint = "done"
	OutputEnterkeyhintEnter    OutputEnterkeyhint = "enter"
)

type OutputHidden string

const (
	OutputHiddenHidden     OutputHidden = "hidden"
	OutputHiddenUntilFound OutputHidden = "until-found"
	OutputHiddenEmpty      OutputHidden = ""
)

type OutputInputmode string

const (
	OutputInputmodeUrl     OutputInputmode = "url"
	OutputInputmodeDecimal OutputInputmode = "decimal"
	OutputInputmodeEmail   OutputInputmode = "email"
	OutputInputmodeNone    OutputInputmode = "none"
	OutputInputmodeNumeric OutputInputmode = "numeric"
	OutputInputmodeSearch  OutputInputmode = "search"
	OutputInputmodeTel     OutputInputmode = "tel"
	OutputInputmodeText    OutputInputmode = "text"
)

type OutputSpellcheck string

const (
	OutputSpellcheckFalse OutputSpellcheck = "false"
	OutputSpellcheckTrue  OutputSpellcheck = "true"
	OutputSpellcheckEmpty OutputSpellcheck = ""
)

type OutputTranslate string

const (
	OutputTranslateNo    OutputTranslate = "no"
	OutputTranslateYes   OutputTranslate = "yes"
	OutputTranslateEmpty OutputTranslate = ""
)

type OutputWritingsuggestions string

const (
	OutputWritingsuggestionsFalse OutputWritingsuggestions = "false"
	OutputWritingsuggestionsTrue  OutputWritingsuggestions = "true"
	OutputWritingsuggestionsEmpty OutputWritingsuggestions = ""
)

type outputAttrs map[string]any

func (e *OutputElement) For(s string) *OutputElement {
	e.attributes["for"] = s

	return e
}

func (e *OutputElement) Form(s string) *OutputElement {
	e.attributes["form"] = s

	return e
}

func (e *OutputElement) Name(s string) *OutputElement {
	e.attributes["name"] = s

	return e
}

func (e *OutputElement) AriaUnsafe(name string, s string) *OutputElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *OutputElement) Aria(name string, s string) *OutputElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *OutputElement) Autocapitalize(a OutputAutocapitalize) *OutputElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *OutputElement) Autocorrect(a OutputAutocorrect) *OutputElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *OutputElement) Autofocus(b bool) *OutputElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *OutputElement) Class(s ...string) *OutputElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *OutputElement) Contenteditable(a OutputContenteditable) *OutputElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *OutputElement) DataUnsafe(name string, s string) *OutputElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *OutputElement) Data(name string, s string) *OutputElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *OutputElement) Dir(a OutputDir) *OutputElement {
	e.attributes["dir"] = a

	return e
}

func (e *OutputElement) Draggable(a OutputDraggable) *OutputElement {
	e.attributes["draggable"] = a

	return e
}

func (e *OutputElement) Enterkeyhint(a OutputEnterkeyhint) *OutputElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *OutputElement) Hidden(a OutputHidden) *OutputElement {
	e.attributes["hidden"] = a

	return e
}

func (e *OutputElement) Id(s string) *OutputElement {
	e.attributes["id"] = s

	return e
}

func (e *OutputElement) Inert(b bool) *OutputElement {
	e.attributes["inert"] = b

	return e
}

func (e *OutputElement) Inputmode(a OutputInputmode) *OutputElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *OutputElement) Itemid(s string) *OutputElement {
	e.attributes["itemid"] = s

	return e
}

func (e *OutputElement) Itemprop(s ...string) *OutputElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *OutputElement) Itemref(s ...string) *OutputElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *OutputElement) Itemscope(b bool) *OutputElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *OutputElement) Itemtype(s ...string) *OutputElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *OutputElement) Lang(s string) *OutputElement {
	e.attributes["lang"] = s

	return e
}

func (e *OutputElement) Nonce(s string) *OutputElement {
	e.attributes["nonce"] = s

	return e
}

func (e *OutputElement) Popover(s string) *OutputElement {
	e.attributes["popover"] = s

	return e
}

func (e *OutputElement) Role(s string) *OutputElement {
	e.attributes["role"] = s

	return e
}

func (e *OutputElement) Slot(s string) *OutputElement {
	e.attributes["slot"] = s

	return e
}

func (e *OutputElement) Spellcheck(a OutputSpellcheck) *OutputElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *OutputElement) Style(s string) *OutputElement {
	e.attributes["style"] = s

	return e
}

func (e *OutputElement) Tabindex(i int) *OutputElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *OutputElement) Title(s string) *OutputElement {
	e.attributes["title"] = s

	return e
}

func (e *OutputElement) Translate(a OutputTranslate) *OutputElement {
	e.attributes["translate"] = a

	return e
}

func (e *OutputElement) Writingsuggestions(a OutputWritingsuggestions) *OutputElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *OutputElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("<output")

	for key, v := range e.attributes {
		sb.WriteByte(' ')
		sb.WriteString(key)

		strVal := fmt.Sprintf("%v", v)
		if strVal != "" {
			sb.WriteByte('=')
			sb.WriteByte('"')
			sb.WriteString(strVal)
			sb.WriteByte('"')
		}
	}

	sb.WriteByte('>')
	for _, child := range e.children {
		if err := child.Render(&sb); err != nil {
			return err
		}
	}

	sb.WriteString("</output>")

	_, err := io.WriteString(w, sb.String())
	return err
}
