// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type SelectedcontentElement struct {
	attributes selectedcontentAttrs
	children   []htemel.Node
	skipRender bool
}

// Selectedcontent creates a tag <selectedcontent> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The selectedcontent element reflects the contents of a select element's currently selected option element. selectedcontent elements can be used to declaratively show the selected option element's contents within the select element's first child button element.
func Selectedcontent(children ...htemel.Node) *SelectedcontentElement {
	node := &SelectedcontentElement{
		children:   children,
		attributes: make(selectedcontentAttrs),
	}

	return node
}

func SelectedcontentIf(condition bool, children ...htemel.Node) *SelectedcontentElement {
	if condition {
		return Selectedcontent(children...)
	}

	return &SelectedcontentElement{
		children:   children,
		attributes: make(selectedcontentAttrs),
		skipRender: true,
	}
}

func SelectedcontentTernary(condition bool, true htemel.Node, false htemel.Node) *SelectedcontentElement {
	if condition {
		return Selectedcontent(true)
	}
	return Selectedcontent(false)
}

// Children appends children to this element.
func (e *SelectedcontentElement) Children(children ...htemel.Node) *SelectedcontentElement {
	e.children = append(e.children, children...)
	return e
}

// With allows passing a function to modify the element via a closure.
func (e *SelectedcontentElement) With(fn func(*SelectedcontentElement)) *SelectedcontentElement {
	fn(e)
	return e
}

// Textf adds a text node to the element with the given format string and arguments.
func (e *SelectedcontentElement) Textf(format string, args ...any) *SelectedcontentElement {
	return e.Children(htemel.Text(fmt.Sprintf(format, args...)))
}

// AddClass appends a class to the element.
func (e *SelectedcontentElement) AddClass(classes ...string) *SelectedcontentElement {
	current := e.attributes["class"].(string)
	all := append(strings.Fields(current), classes...)
	e.attributes["class"] = strings.Join(all, " ")
	return e
}

// ToggleClass toggles a class on or off.
func (e *SelectedcontentElement) ToggleClass(class string, enable bool) *SelectedcontentElement {
	classes := strings.Fields(e.attributes["class"].(string))
	idx := slices.Index(classes, class)
	if enable && idx == -1 {
		classes = append(classes, class)
	} else if !enable && idx >= 0 {
		classes = slices.Delete(classes, idx, idx+1)
	}
	e.attributes["class"] = strings.Join(classes, " ")
	return e
}

type SelectedcontentAutocapitalize string

const (
	SelectedcontentAutocapitalizeCharacters SelectedcontentAutocapitalize = "characters"
	SelectedcontentAutocapitalizeNone       SelectedcontentAutocapitalize = "none"
	SelectedcontentAutocapitalizeOff        SelectedcontentAutocapitalize = "off"
	SelectedcontentAutocapitalizeOn         SelectedcontentAutocapitalize = "on"
	SelectedcontentAutocapitalizeSentences  SelectedcontentAutocapitalize = "sentences"
	SelectedcontentAutocapitalizeWords      SelectedcontentAutocapitalize = "words"
)

type SelectedcontentAutocorrect string

const (
	SelectedcontentAutocorrectOff   SelectedcontentAutocorrect = "off"
	SelectedcontentAutocorrectOn    SelectedcontentAutocorrect = "on"
	SelectedcontentAutocorrectEmpty SelectedcontentAutocorrect = ""
)

type SelectedcontentContenteditable string

const (
	SelectedcontentContenteditableFalse         SelectedcontentContenteditable = "false"
	SelectedcontentContenteditablePlaintextOnly SelectedcontentContenteditable = "plaintext-only"
	SelectedcontentContenteditableTrue          SelectedcontentContenteditable = "true"
	SelectedcontentContenteditableEmpty         SelectedcontentContenteditable = ""
)

type SelectedcontentDir string

const (
	SelectedcontentDirAuto SelectedcontentDir = "auto"
	SelectedcontentDirLtr  SelectedcontentDir = "ltr"
	SelectedcontentDirRtl  SelectedcontentDir = "rtl"
)

type SelectedcontentDraggable string

const (
	SelectedcontentDraggableFalse SelectedcontentDraggable = "false"
	SelectedcontentDraggableTrue  SelectedcontentDraggable = "true"
)

type SelectedcontentEnterkeyhint string

const (
	SelectedcontentEnterkeyhintEnter    SelectedcontentEnterkeyhint = "enter"
	SelectedcontentEnterkeyhintGo       SelectedcontentEnterkeyhint = "go"
	SelectedcontentEnterkeyhintNext     SelectedcontentEnterkeyhint = "next"
	SelectedcontentEnterkeyhintPrevious SelectedcontentEnterkeyhint = "previous"
	SelectedcontentEnterkeyhintSearch   SelectedcontentEnterkeyhint = "search"
	SelectedcontentEnterkeyhintSend     SelectedcontentEnterkeyhint = "send"
	SelectedcontentEnterkeyhintDone     SelectedcontentEnterkeyhint = "done"
)

type SelectedcontentHidden string

const (
	SelectedcontentHiddenHidden     SelectedcontentHidden = "hidden"
	SelectedcontentHiddenUntilFound SelectedcontentHidden = "until-found"
	SelectedcontentHiddenEmpty      SelectedcontentHidden = ""
)

type SelectedcontentInputmode string

const (
	SelectedcontentInputmodeUrl     SelectedcontentInputmode = "url"
	SelectedcontentInputmodeDecimal SelectedcontentInputmode = "decimal"
	SelectedcontentInputmodeEmail   SelectedcontentInputmode = "email"
	SelectedcontentInputmodeNone    SelectedcontentInputmode = "none"
	SelectedcontentInputmodeNumeric SelectedcontentInputmode = "numeric"
	SelectedcontentInputmodeSearch  SelectedcontentInputmode = "search"
	SelectedcontentInputmodeTel     SelectedcontentInputmode = "tel"
	SelectedcontentInputmodeText    SelectedcontentInputmode = "text"
)

type SelectedcontentSpellcheck string

const (
	SelectedcontentSpellcheckFalse SelectedcontentSpellcheck = "false"
	SelectedcontentSpellcheckTrue  SelectedcontentSpellcheck = "true"
	SelectedcontentSpellcheckEmpty SelectedcontentSpellcheck = ""
)

type SelectedcontentTranslate string

const (
	SelectedcontentTranslateNo    SelectedcontentTranslate = "no"
	SelectedcontentTranslateYes   SelectedcontentTranslate = "yes"
	SelectedcontentTranslateEmpty SelectedcontentTranslate = ""
)

type SelectedcontentWritingsuggestions string

const (
	SelectedcontentWritingsuggestionsFalse SelectedcontentWritingsuggestions = "false"
	SelectedcontentWritingsuggestionsTrue  SelectedcontentWritingsuggestions = "true"
	SelectedcontentWritingsuggestionsEmpty SelectedcontentWritingsuggestions = ""
)

type selectedcontentAttrs map[string]any

func (e *SelectedcontentElement) AriaUnsafe(name string, s string) *SelectedcontentElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *SelectedcontentElement) Aria(name string, s string) *SelectedcontentElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *SelectedcontentElement) Autocapitalize(a SelectedcontentAutocapitalize) *SelectedcontentElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *SelectedcontentElement) Autocorrect(a SelectedcontentAutocorrect) *SelectedcontentElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *SelectedcontentElement) Autofocus(b bool) *SelectedcontentElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *SelectedcontentElement) Class(s ...string) *SelectedcontentElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *SelectedcontentElement) Contenteditable(a SelectedcontentContenteditable) *SelectedcontentElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *SelectedcontentElement) DataUnsafe(name string, s string) *SelectedcontentElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *SelectedcontentElement) Data(name string, s string) *SelectedcontentElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *SelectedcontentElement) Dir(a SelectedcontentDir) *SelectedcontentElement {
	e.attributes["dir"] = a

	return e
}

func (e *SelectedcontentElement) Draggable(a SelectedcontentDraggable) *SelectedcontentElement {
	e.attributes["draggable"] = a

	return e
}

func (e *SelectedcontentElement) Enterkeyhint(a SelectedcontentEnterkeyhint) *SelectedcontentElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *SelectedcontentElement) Hidden(a SelectedcontentHidden) *SelectedcontentElement {
	e.attributes["hidden"] = a

	return e
}

func (e *SelectedcontentElement) Id(s string) *SelectedcontentElement {
	e.attributes["id"] = s

	return e
}

func (e *SelectedcontentElement) Inert(b bool) *SelectedcontentElement {
	e.attributes["inert"] = b

	return e
}

func (e *SelectedcontentElement) Inputmode(a SelectedcontentInputmode) *SelectedcontentElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *SelectedcontentElement) Itemid(s string) *SelectedcontentElement {
	e.attributes["itemid"] = s

	return e
}

func (e *SelectedcontentElement) Itemprop(s ...string) *SelectedcontentElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *SelectedcontentElement) Itemref(s ...string) *SelectedcontentElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *SelectedcontentElement) Itemscope(b bool) *SelectedcontentElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *SelectedcontentElement) Itemtype(s ...string) *SelectedcontentElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *SelectedcontentElement) Lang(s string) *SelectedcontentElement {
	e.attributes["lang"] = s

	return e
}

func (e *SelectedcontentElement) Nonce(s string) *SelectedcontentElement {
	e.attributes["nonce"] = s

	return e
}

func (e *SelectedcontentElement) Popover(s string) *SelectedcontentElement {
	e.attributes["popover"] = s

	return e
}

func (e *SelectedcontentElement) Role(s string) *SelectedcontentElement {
	e.attributes["role"] = s

	return e
}

func (e *SelectedcontentElement) Slot(s string) *SelectedcontentElement {
	e.attributes["slot"] = s

	return e
}

func (e *SelectedcontentElement) Spellcheck(a SelectedcontentSpellcheck) *SelectedcontentElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *SelectedcontentElement) Style(s string) *SelectedcontentElement {
	e.attributes["style"] = s

	return e
}

func (e *SelectedcontentElement) Tabindex(i int) *SelectedcontentElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *SelectedcontentElement) Title(s string) *SelectedcontentElement {
	e.attributes["title"] = s

	return e
}

func (e *SelectedcontentElement) Translate(a SelectedcontentTranslate) *SelectedcontentElement {
	e.attributes["translate"] = a

	return e
}

func (e *SelectedcontentElement) Writingsuggestions(a SelectedcontentWritingsuggestions) *SelectedcontentElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *SelectedcontentElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<selectedcontent")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</selectedcontent>")); err != nil {
		return err
	}

	return nil
}
