// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type TextareaElement struct {
	attributes textareaAttrs
	children   []htemel.Node
	skipRender bool
}

// Textarea creates a tag <textarea> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The textarea element represents a multiline plain text edit control for the element's raw value. The contents of the control represent the control's default value.
func Textarea(children ...htemel.Node) *TextareaElement {
	node := &TextareaElement{
		children:   children,
		attributes: make(textareaAttrs),
	}

	return node
}

func TextareaIf(condition bool, children ...htemel.Node) *TextareaElement {
	if condition {
		return Textarea(children...)
	}

	return &TextareaElement{
		children:   children,
		attributes: make(textareaAttrs),
		skipRender: true,
	}
}

func TextareaTernary(condition bool, true htemel.Node, false htemel.Node) *TextareaElement {
	if condition {
		return Textarea(true)
	}

	return Textarea(false)
}

type TextareaWrap string

const (
	TextareaWrapHard TextareaWrap = "hard"
	TextareaWrapSoft TextareaWrap = "soft"
)

type TextareaAutocapitalize string

const (
	TextareaAutocapitalizeCharacters TextareaAutocapitalize = "characters"
	TextareaAutocapitalizeNone       TextareaAutocapitalize = "none"
	TextareaAutocapitalizeOff        TextareaAutocapitalize = "off"
	TextareaAutocapitalizeOn         TextareaAutocapitalize = "on"
	TextareaAutocapitalizeSentences  TextareaAutocapitalize = "sentences"
	TextareaAutocapitalizeWords      TextareaAutocapitalize = "words"
)

type TextareaAutocorrect string

const (
	TextareaAutocorrectOff   TextareaAutocorrect = "off"
	TextareaAutocorrectOn    TextareaAutocorrect = "on"
	TextareaAutocorrectEmpty TextareaAutocorrect = ""
)

type TextareaContenteditable string

const (
	TextareaContenteditableFalse         TextareaContenteditable = "false"
	TextareaContenteditablePlaintextOnly TextareaContenteditable = "plaintext-only"
	TextareaContenteditableTrue          TextareaContenteditable = "true"
	TextareaContenteditableEmpty         TextareaContenteditable = ""
)

type TextareaDir string

const (
	TextareaDirAuto TextareaDir = "auto"
	TextareaDirLtr  TextareaDir = "ltr"
	TextareaDirRtl  TextareaDir = "rtl"
)

type TextareaDraggable string

const (
	TextareaDraggableTrue  TextareaDraggable = "true"
	TextareaDraggableFalse TextareaDraggable = "false"
)

type TextareaEnterkeyhint string

const (
	TextareaEnterkeyhintDone     TextareaEnterkeyhint = "done"
	TextareaEnterkeyhintEnter    TextareaEnterkeyhint = "enter"
	TextareaEnterkeyhintGo       TextareaEnterkeyhint = "go"
	TextareaEnterkeyhintNext     TextareaEnterkeyhint = "next"
	TextareaEnterkeyhintPrevious TextareaEnterkeyhint = "previous"
	TextareaEnterkeyhintSearch   TextareaEnterkeyhint = "search"
	TextareaEnterkeyhintSend     TextareaEnterkeyhint = "send"
)

type TextareaHidden string

const (
	TextareaHiddenHidden     TextareaHidden = "hidden"
	TextareaHiddenUntilFound TextareaHidden = "until-found"
	TextareaHiddenEmpty      TextareaHidden = ""
)

type TextareaInputmode string

const (
	TextareaInputmodeTel     TextareaInputmode = "tel"
	TextareaInputmodeText    TextareaInputmode = "text"
	TextareaInputmodeUrl     TextareaInputmode = "url"
	TextareaInputmodeDecimal TextareaInputmode = "decimal"
	TextareaInputmodeEmail   TextareaInputmode = "email"
	TextareaInputmodeNone    TextareaInputmode = "none"
	TextareaInputmodeNumeric TextareaInputmode = "numeric"
	TextareaInputmodeSearch  TextareaInputmode = "search"
)

type TextareaSpellcheck string

const (
	TextareaSpellcheckFalse TextareaSpellcheck = "false"
	TextareaSpellcheckTrue  TextareaSpellcheck = "true"
	TextareaSpellcheckEmpty TextareaSpellcheck = ""
)

type TextareaTranslate string

const (
	TextareaTranslateNo    TextareaTranslate = "no"
	TextareaTranslateYes   TextareaTranslate = "yes"
	TextareaTranslateEmpty TextareaTranslate = ""
)

type TextareaWritingsuggestions string

const (
	TextareaWritingsuggestionsTrue  TextareaWritingsuggestions = "true"
	TextareaWritingsuggestionsFalse TextareaWritingsuggestions = "false"
	TextareaWritingsuggestionsEmpty TextareaWritingsuggestions = ""
)

type textareaAttrs map[string]any

func (e *TextareaElement) Autocomplete(s string) *TextareaElement {
	e.attributes["autocomplete"] = s

	return e
}

func (e *TextareaElement) Cols(i int) *TextareaElement {
	e.attributes["cols"] = i

	return e
}

func (e *TextareaElement) Dirname(s string) *TextareaElement {
	e.attributes["dirname"] = s

	return e
}

func (e *TextareaElement) Disabled(b bool) *TextareaElement {
	e.attributes["disabled"] = b

	return e
}

func (e *TextareaElement) Form(s string) *TextareaElement {
	e.attributes["form"] = s

	return e
}

func (e *TextareaElement) Maxlength(i int) *TextareaElement {
	e.attributes["maxlength"] = i

	return e
}

func (e *TextareaElement) Minlength(i int) *TextareaElement {
	e.attributes["minlength"] = i

	return e
}

func (e *TextareaElement) Name(s string) *TextareaElement {
	e.attributes["name"] = s

	return e
}

func (e *TextareaElement) Placeholder(s string) *TextareaElement {
	e.attributes["placeholder"] = s

	return e
}

func (e *TextareaElement) Readonly(b bool) *TextareaElement {
	e.attributes["readonly"] = b

	return e
}

func (e *TextareaElement) Required(b bool) *TextareaElement {
	e.attributes["required"] = b

	return e
}

func (e *TextareaElement) Rows(s string) *TextareaElement {
	e.attributes["rows"] = s

	return e
}

func (e *TextareaElement) Wrap(a TextareaWrap) *TextareaElement {
	e.attributes["wrap"] = a

	return e
}

func (e *TextareaElement) AriaUnsafe(name string, s string) *TextareaElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *TextareaElement) Aria(name string, s string) *TextareaElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *TextareaElement) Autocapitalize(a TextareaAutocapitalize) *TextareaElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *TextareaElement) Autocorrect(a TextareaAutocorrect) *TextareaElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *TextareaElement) Autofocus(b bool) *TextareaElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *TextareaElement) Class(s ...string) *TextareaElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *TextareaElement) Contenteditable(a TextareaContenteditable) *TextareaElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *TextareaElement) DataUnsafe(name string, s string) *TextareaElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *TextareaElement) Data(name string, s string) *TextareaElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *TextareaElement) Dir(a TextareaDir) *TextareaElement {
	e.attributes["dir"] = a

	return e
}

func (e *TextareaElement) Draggable(a TextareaDraggable) *TextareaElement {
	e.attributes["draggable"] = a

	return e
}

func (e *TextareaElement) Enterkeyhint(a TextareaEnterkeyhint) *TextareaElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *TextareaElement) Hidden(a TextareaHidden) *TextareaElement {
	e.attributes["hidden"] = a

	return e
}

func (e *TextareaElement) Id(s string) *TextareaElement {
	e.attributes["id"] = s

	return e
}

func (e *TextareaElement) Inert(b bool) *TextareaElement {
	e.attributes["inert"] = b

	return e
}

func (e *TextareaElement) Inputmode(a TextareaInputmode) *TextareaElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *TextareaElement) Itemid(s string) *TextareaElement {
	e.attributes["itemid"] = s

	return e
}

func (e *TextareaElement) Itemprop(s ...string) *TextareaElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *TextareaElement) Itemref(s ...string) *TextareaElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *TextareaElement) Itemscope(b bool) *TextareaElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *TextareaElement) Itemtype(s ...string) *TextareaElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *TextareaElement) Lang(s string) *TextareaElement {
	e.attributes["lang"] = s

	return e
}

func (e *TextareaElement) Nonce(s string) *TextareaElement {
	e.attributes["nonce"] = s

	return e
}

func (e *TextareaElement) Popover(s string) *TextareaElement {
	e.attributes["popover"] = s

	return e
}

func (e *TextareaElement) Slot(s string) *TextareaElement {
	e.attributes["slot"] = s

	return e
}

func (e *TextareaElement) Spellcheck(a TextareaSpellcheck) *TextareaElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *TextareaElement) Style(s string) *TextareaElement {
	e.attributes["style"] = s

	return e
}

func (e *TextareaElement) Tabindex(i int) *TextareaElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *TextareaElement) Title(s string) *TextareaElement {
	e.attributes["title"] = s

	return e
}

func (e *TextareaElement) Translate(a TextareaTranslate) *TextareaElement {
	e.attributes["translate"] = a

	return e
}

func (e *TextareaElement) Writingsuggestions(a TextareaWritingsuggestions) *TextareaElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *TextareaElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<textarea")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</textarea>")); err != nil {
		return err
	}

	return nil
}
