// Code generated by htemel. DO NOT EDIT.
package html

import (
	"fmt"
	"io"
	"strings"

	"github.com/derekmwright/htemel"
	"golang.org/x/net/html"
)

type UElement struct {
	attributes uAttrs
	children   []htemel.Node
	skipRender bool
}

// U creates a tag <u> instance and returns it for further modification.
// Any children passed will be nested within the tag.//
// Spec Description: The u element represents a span of text with an unarticulated, though explicitly rendered, non-textual annotation, such as labeling the text as being a proper name in Chinese text (a Chinese proper name mark), or labeling the text as being misspelt.
func U(children ...htemel.Node) *UElement {
	node := &UElement{
		children:   children,
		attributes: make(uAttrs),
	}

	return node
}

func UIf(condition bool, children ...htemel.Node) *UElement {
	if condition {
		return U(children...)
	}

	return &UElement{
		children:   children,
		attributes: make(uAttrs),
		skipRender: true,
	}
}

func UTernary(condition bool, true htemel.Node, false htemel.Node) *UElement {
	if condition {
		return U(true)
	}

	return U(false)
}

type UAutocapitalize string

const (
	UAutocapitalizeOn         UAutocapitalize = "on"
	UAutocapitalizeSentences  UAutocapitalize = "sentences"
	UAutocapitalizeWords      UAutocapitalize = "words"
	UAutocapitalizeCharacters UAutocapitalize = "characters"
	UAutocapitalizeNone       UAutocapitalize = "none"
	UAutocapitalizeOff        UAutocapitalize = "off"
)

type UAutocorrect string

const (
	UAutocorrectOff   UAutocorrect = "off"
	UAutocorrectOn    UAutocorrect = "on"
	UAutocorrectEmpty UAutocorrect = ""
)

type UContenteditable string

const (
	UContenteditableFalse         UContenteditable = "false"
	UContenteditablePlaintextOnly UContenteditable = "plaintext-only"
	UContenteditableTrue          UContenteditable = "true"
	UContenteditableEmpty         UContenteditable = ""
)

type UDir string

const (
	UDirRtl  UDir = "rtl"
	UDirAuto UDir = "auto"
	UDirLtr  UDir = "ltr"
)

type UDraggable string

const (
	UDraggableFalse UDraggable = "false"
	UDraggableTrue  UDraggable = "true"
)

type UEnterkeyhint string

const (
	UEnterkeyhintSend     UEnterkeyhint = "send"
	UEnterkeyhintDone     UEnterkeyhint = "done"
	UEnterkeyhintEnter    UEnterkeyhint = "enter"
	UEnterkeyhintGo       UEnterkeyhint = "go"
	UEnterkeyhintNext     UEnterkeyhint = "next"
	UEnterkeyhintPrevious UEnterkeyhint = "previous"
	UEnterkeyhintSearch   UEnterkeyhint = "search"
)

type UHidden string

const (
	UHiddenUntilFound UHidden = "until-found"
	UHiddenHidden     UHidden = "hidden"
	UHiddenEmpty      UHidden = ""
)

type UInputmode string

const (
	UInputmodeTel     UInputmode = "tel"
	UInputmodeText    UInputmode = "text"
	UInputmodeUrl     UInputmode = "url"
	UInputmodeDecimal UInputmode = "decimal"
	UInputmodeEmail   UInputmode = "email"
	UInputmodeNone    UInputmode = "none"
	UInputmodeNumeric UInputmode = "numeric"
	UInputmodeSearch  UInputmode = "search"
)

type USpellcheck string

const (
	USpellcheckFalse USpellcheck = "false"
	USpellcheckTrue  USpellcheck = "true"
	USpellcheckEmpty USpellcheck = ""
)

type UTranslate string

const (
	UTranslateYes   UTranslate = "yes"
	UTranslateNo    UTranslate = "no"
	UTranslateEmpty UTranslate = ""
)

type UWritingsuggestions string

const (
	UWritingsuggestionsFalse UWritingsuggestions = "false"
	UWritingsuggestionsTrue  UWritingsuggestions = "true"
	UWritingsuggestionsEmpty UWritingsuggestions = ""
)

type uAttrs map[string]any

func (e *UElement) AriaUnsafe(name string, s string) *UElement {
	tag := strings.ToLower("aria-" + name)

	e.attributes[tag] = s

	return e
}

func (e *UElement) Aria(name string, s string) *UElement {
	return e.AriaUnsafe(name, html.EscapeString(s))
}

func (e *UElement) Autocapitalize(a UAutocapitalize) *UElement {
	e.attributes["autocapitalize"] = a

	return e
}

func (e *UElement) Autocorrect(a UAutocorrect) *UElement {
	e.attributes["autocorrect"] = a

	return e
}

func (e *UElement) Autofocus(b bool) *UElement {
	e.attributes["autofocus"] = b

	return e
}

func (e *UElement) Class(s ...string) *UElement {
	e.attributes["class"] = strings.Join(s, " ")

	return e
}

func (e *UElement) Contenteditable(a UContenteditable) *UElement {
	e.attributes["contenteditable"] = a

	return e
}

func (e *UElement) DataUnsafe(name string, s string) *UElement {
	tag := strings.ToLower("data-" + name)

	e.attributes[tag] = s

	return e
}

func (e *UElement) Data(name string, s string) *UElement {
	return e.DataUnsafe(name, html.EscapeString(s))
}

func (e *UElement) Dir(a UDir) *UElement {
	e.attributes["dir"] = a

	return e
}

func (e *UElement) Draggable(a UDraggable) *UElement {
	e.attributes["draggable"] = a

	return e
}

func (e *UElement) Enterkeyhint(a UEnterkeyhint) *UElement {
	e.attributes["enterkeyhint"] = a

	return e
}

func (e *UElement) Hidden(a UHidden) *UElement {
	e.attributes["hidden"] = a

	return e
}

func (e *UElement) Id(s string) *UElement {
	e.attributes["id"] = s

	return e
}

func (e *UElement) Inert(b bool) *UElement {
	e.attributes["inert"] = b

	return e
}

func (e *UElement) Inputmode(a UInputmode) *UElement {
	e.attributes["inputmode"] = a

	return e
}

func (e *UElement) Itemid(s string) *UElement {
	e.attributes["itemid"] = s

	return e
}

func (e *UElement) Itemprop(s ...string) *UElement {
	e.attributes["itemprop"] = strings.Join(s, " ")

	return e
}

func (e *UElement) Itemref(s ...string) *UElement {
	e.attributes["itemref"] = strings.Join(s, " ")

	return e
}

func (e *UElement) Itemscope(b bool) *UElement {
	e.attributes["itemscope"] = b

	return e
}

func (e *UElement) Itemtype(s ...string) *UElement {
	e.attributes["itemtype"] = strings.Join(s, " ")

	return e
}

func (e *UElement) Lang(s string) *UElement {
	e.attributes["lang"] = s

	return e
}

func (e *UElement) Nonce(s string) *UElement {
	e.attributes["nonce"] = s

	return e
}

func (e *UElement) Popover(s string) *UElement {
	e.attributes["popover"] = s

	return e
}

func (e *UElement) Slot(s string) *UElement {
	e.attributes["slot"] = s

	return e
}

func (e *UElement) Spellcheck(a USpellcheck) *UElement {
	e.attributes["spellcheck"] = a

	return e
}

func (e *UElement) Style(s string) *UElement {
	e.attributes["style"] = s

	return e
}

func (e *UElement) Tabindex(i int) *UElement {
	e.attributes["tabindex"] = i

	return e
}

func (e *UElement) Title(s string) *UElement {
	e.attributes["title"] = s

	return e
}

func (e *UElement) Translate(a UTranslate) *UElement {
	e.attributes["translate"] = a

	return e
}

func (e *UElement) Writingsuggestions(a UWritingsuggestions) *UElement {
	e.attributes["writingsuggestions"] = a

	return e
}

// Render processes the current element, and writes the initial tag.
// Then all children are processed and included within the tag.
// Finally, the tag is closed.
//
// *Except for void elements as they are self closing and do not contain children.
func (e *UElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<u")); err != nil {
		return err
	}

	c := len(e.attributes)
	i := 1
	for key, v := range e.attributes {
		if i == 1 {
			w.Write([]byte(" "))
		}

		w.Write([]byte(key))

		// Enum types support empty attributes and can be omitted.
		if fmt.Sprintf("%s", v) == "" {
			w.Write([]byte(" "))
			continue
		}

		w.Write([]byte("="))

		w.Write([]byte("\"" + fmt.Sprintf("%v", v) + "\""))

		if i < c {
			w.Write([]byte(" "))
		}

		i++
	}

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}
	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</u>")); err != nil {
		return err
	}

	return nil
}
