// Code generated by htemel. DO NOT EDIT.
package html

import (
  "github.com/derekmwright/htemel"
  "io"
)

type WbrElement struct {
	children []htemel.Node
	skipRender bool
}

// Wbr creates a tag <wbr> instance and returns it for further modification.
// Any children passed will be nested within the tag.
//
// Spec Description: The wbr element represents a line break opportunity.
func Wbr(children ...htemel.Node) *WbrElement {
	node := &WbrElement{
		children: children,
	}

	return node
}

func WbrIf(condition bool, children ...htemel.Node) *WbrElement {
	if condition {
		return Wbr(children...)
	}

	return &WbrElement{
		skipRender: true,
	}
}

func (e *WbrElement) Render(w io.Writer) error {
	if e.skipRender {
		return nil
	}

	if _, err := w.Write([]byte("<wbr")); err != nil {
		return err
	}

	// TODO: Attribute stuff here

	if _, err := w.Write([]byte(">")); err != nil {
		return err
	}

	for _, child := range e.children {
		if err := child.Render(w); err != nil {
			return err
		}
	}

	if _, err := w.Write([]byte("</wbr>")); err != nil {
		return err
	}

	return nil
}
